import { CURRENT_ORG_ID } from "./constants";
import {
  activity,
  adj,
  buildPeriod,
  contact,
  doc,
  fact,
  inference,
  req,
  task,
} from "./seed-helpers";
import type { Database, Deal } from "./types";

const ORG = CURRENT_ORG_ID;
const ELENA = "user_elena";
const MARCUS = "user_marcus";
const PRIYA = "user_priya";
const ALEX = "user_alex";
const TOM = "user_tom";

function emptyRelated(): Pick<
  Database,
  | "contacts"
  | "financial_periods"
  | "financial_metrics"
  | "ebitda_adjustments"
  | "documents"
  | "diligence_requests"
  | "ai_findings"
  | "tasks"
  | "notes"
  | "activities"
  | "audit_events"
> {
  return {
    contacts: [],
    financial_periods: [],
    financial_metrics: [],
    ebitda_adjustments: [],
    documents: [],
    diligence_requests: [],
    ai_findings: [],
    tasks: [],
    notes: [],
    activities: [],
    audit_events: [],
  };
}

function merge(
  ...slices: ReturnType<typeof emptyRelated>[]
): ReturnType<typeof emptyRelated> {
  const out = emptyRelated();
  for (const slice of slices) {
    (Object.keys(out) as (keyof typeof out)[]).forEach((key) => {
      // @ts-expect-error concat typed tables
      out[key] = out[key].concat(slice[key]);
    });
  }
  return out;
}

export const portfolioDeals: Deal[] = [
  {
    id: "whitaker-dunn",
    organization_id: ORG,
    name: "Whitaker Dunn",
    location_city: "Atlanta",
    location_state: "GA",
    owner_user_id: ELENA,
    source: "proprietary",
    source_detail: "Elena outbound",
    stage: "financial_review",
    stage_entered_at: "2026-08-11",
    asking_price: 7_150_000,
    expected_purchase_price: 7_150_000,
    probability: 0.4,
    vertical: "legal",
    vertical_metrics: {
      attorney_count: 11,
      partner_count: 3,
      revenue_per_attorney: 472_727,
      revenue_concentration_top3: 0.44,
      practice_area_mix: [
        { name: "Corporate", share: 0.48 },
        { name: "Employment", share: 0.27 },
        { name: "Other", share: 0.25 },
      ],
    },
    flags: ["working_capital"],
    created_at: "2026-07-08T14:00:00.000Z",
    last_activity_at: "2026-08-21T16:00:00.000Z",
    summary:
      "Mid-market Atlanta corporate shop. Elena sourced it directly after a bar dinner. TTM-equivalent FY2024 revenue is $5.2M with $1.1M reported EBITDA. In financial review; add-back interview is scheduled and working-capital seasonality is the open underwriting question.",
    ai_assessment:
      "FY2024 revenue of $5.2M is up 7.2% from FY2023. No accepted adjustments yet; a $80k occupancy add-back remains proposed. Reported margin is 21.2%. Concentration in the top three attorneys is 44% — higher than Hale, still below the Voss threshold that caused a pass.",
    attention_items: [
      "Working-capital seasonality not yet modeled",
      "Occupancy add-back still proposed",
    ],
  },
  {
    id: "miller-law",
    organization_id: ORG,
    name: "Miller Law Group",
    location_city: "Dallas",
    location_state: "TX",
    owner_user_id: PRIYA,
    source: "banker",
    source_detail: "Robert W. Baird",
    stage: "confirmatory_diligence",
    stage_entered_at: "2026-07-28",
    asking_price: 21_000_000,
    expected_purchase_price: 21_000_000,
    probability: 0.7,
    vertical: "legal",
    vertical_metrics: {
      attorney_count: 32,
      partner_count: 8,
      revenue_per_attorney: 356_250,
      revenue_concentration_top3: 0.22,
      practice_area_mix: [
        { name: "Litigation", share: 0.36 },
        { name: "Corporate", share: 0.34 },
        { name: "Energy", share: 0.18 },
        { name: "Other", share: 0.12 },
      ],
    },
    flags: ["missing_tax_return", "malpractice"],
    created_at: "2026-05-04T12:00:00.000Z",
    last_activity_at: "2026-08-25T19:10:00.000Z",
    summary:
      "Largest live process. Dallas platform candidate at $11.4M revenue and $2.8M reported EBITDA, $21.0M expected price. LOI is signed; confirmatory is gated on the client list, 2025 tax return, and five-year malpractice history — all still outstanding from the seller.",
    ai_assessment:
      "Accepted owner-compensation normalization of $150k takes adjusted EBITDA to $2.95M (7.1x). Client-level concentration looks healthier than the rest of the book (top-3 22%), but we cannot underwrite that until the client list arrives. Malpractice loss runs are the other confirmatory blocker.",
    attention_items: [
      "Client list still outstanding",
      "2025 tax return not received",
      "Malpractice claims history not received",
    ],
  },
  {
    id: "rhodes-pell",
    organization_id: ORG,
    name: "Rhodes & Pell",
    location_city: "Denver",
    location_state: "CO",
    owner_user_id: ELENA,
    source: "conference",
    source_detail: "Legalweek",
    stage: "loi",
    stage_entered_at: "2026-08-06",
    asking_price: 11_200_000,
    expected_purchase_price: 11_200_000,
    probability: 0.65,
    vertical: "legal",
    vertical_metrics: {
      attorney_count: 14,
      partner_count: 4,
      revenue_per_attorney: 485_714,
      revenue_concentration_top3: 0.29,
      practice_area_mix: [
        { name: "Real Estate", share: 0.41 },
        { name: "Corporate", share: 0.33 },
        { name: "Other", share: 0.26 },
      ],
    },
    flags: [],
    created_at: "2026-06-02T10:00:00.000Z",
    last_activity_at: "2026-08-19T14:20:00.000Z",
    summary:
      "Denver real-estate-weighted firm. LOI signed 6 Aug at $11.2M (7.0x reported). Confirmatory request list has not been issued. FY2024 revenue $6.8M, reported EBITDA $1.6M; a $75k one-time add-back is already accepted.",
    ai_assessment:
      "Cleanest process in the book after Brennan Cole. Normalized EBITDA is $1.675M. Real-estate mix (41%) tracks Northline's existing Denver office better than a litigation-heavy book. Confirmatory has not started — the next miss is calendar, not substance.",
    attention_items: ["Confirmatory request list not yet sent"],
  },
  {
    id: "sato-barrett",
    organization_id: ORG,
    name: "Sato Barrett",
    location_city: "Los Angeles",
    location_state: "CA",
    owner_user_id: MARCUS,
    source: "counsel_intro",
    source_detail: "Latham referral",
    stage: "initial_data",
    stage_entered_at: "2026-08-18",
    asking_price: 4_320_000,
    expected_purchase_price: 4_320_000,
    probability: 0.3,
    vertical: "legal",
    vertical_metrics: {
      attorney_count: 9,
      partner_count: 2,
      revenue_per_attorney: 455_556,
      revenue_concentration_top3: 0.51,
      practice_area_mix: [
        { name: "Entertainment", share: 0.46 },
        { name: "Corporate", share: 0.32 },
        { name: "Other", share: 0.22 },
      ],
    },
    flags: ["data_room_thin", "concentration"],
    created_at: "2026-08-03T09:00:00.000Z",
    last_activity_at: "2026-08-22T11:00:00.000Z",
    summary:
      "Los Angeles entertainment/corporate boutique. Data room opened 18 Aug; only the CIM and a one-year P&L are in. FY2024 revenue $4.1M, reported EBITDA $720k, 17.6% margin. Too early to normalize.",
    ai_assessment:
      "At 6.0x reported the entry multiple is not demanding, but top-3 concentration is 51% and the room is thin. Do not treat $720k as a quality-of-earnings number until a second year and payroll land.",
    attention_items: ["Data room just opened — missing tax, payroll, and production"],
  },
  {
    id: "quinn-harbor",
    organization_id: ORG,
    name: "Quinn Harbor LLP",
    location_city: "Boston",
    location_state: "MA",
    owner_user_id: PRIYA,
    source: "banker",
    source_detail: "Raymond James",
    stage: "nda",
    stage_entered_at: "2026-07-22",
    asking_price: 15_400_000,
    expected_purchase_price: 15_400_000,
    probability: 0.25,
    vertical: "legal",
    vertical_metrics: {
      attorney_count: 21,
      partner_count: 6,
      revenue_per_attorney: 457_143,
      revenue_concentration_top3: 0.27,
    },
    flags: ["stale"],
    created_at: "2026-07-09T15:30:00.000Z",
    last_activity_at: "2026-08-08T12:00:00.000Z",
    summary:
      "Boston harbor-adjacent litigation firm, $9.6M revenue and $2.2M reported EBITDA. NDA has been in counsel review since late July. Process is stalling; last activity 8 Aug.",
    ai_assessment:
      "Scale is attractive (21 attorneys) and concentration is moderate. Until the NDA clears we have only CIM figures. Treat $2.2M EBITDA as a banker representation, not a source fact.",
    attention_items: ["NDA still in counsel review", "No activity in 19 days"],
  },
  {
    id: "keller-frost",
    organization_id: ORG,
    name: "Keller Frost",
    location_city: "Minneapolis",
    location_state: "MN",
    owner_user_id: TOM,
    source: "proprietary",
    source_detail: "Tom outreach",
    stage: "contacted",
    stage_entered_at: "2026-08-19",
    asking_price: 3_480_000,
    expected_purchase_price: 3_480_000,
    probability: 0.15,
    vertical: "legal",
    vertical_metrics: {
      attorney_count: 7,
      partner_count: 2,
      revenue_per_attorney: 485_714,
      revenue_concentration_top3: 0.58,
    },
    flags: ["key_person"],
    created_at: "2026-08-12T16:00:00.000Z",
    last_activity_at: "2026-08-20T17:45:00.000Z",
    summary:
      "Seven-attorney Minneapolis firm. First call last week with Pat Keller. FY2024 revenue $3.4M, reported EBITDA $580k. Early and founder-dependent.",
    ai_assessment:
      "Entry is a conversation, not a process. $580k on $3.4M is a 17.1% margin — plausible for a lean shop, unverified. Second call is scheduled; do not staff diligence until a CIM or P&L arrives.",
    attention_items: ["First call completed; second call not yet held"],
  },
  {
    id: "ortiz-lang",
    organization_id: ORG,
    name: "Ortiz Lang",
    location_city: "Phoenix",
    location_state: "AZ",
    owner_user_id: TOM,
    source: "conference",
    source_detail: "ABA annual",
    stage: "target",
    stage_entered_at: "2026-07-02",
    asking_price: 2_460_000,
    expected_purchase_price: 2_460_000,
    probability: 0.1,
    vertical: "legal",
    vertical_metrics: {
      attorney_count: 6,
      partner_count: 2,
      revenue_per_attorney: 483_333,
      revenue_concentration_top3: 0.62,
    },
    flags: ["stale"],
    created_at: "2026-07-02T11:00:00.000Z",
    last_activity_at: "2026-07-18T09:30:00.000Z",
    summary:
      "Phoenix target identified at the ABA meeting. FY2024 revenue $2.9M, reported EBITDA $410k. Not yet contacted. Intro email is overdue.",
    ai_assessment:
      "Smallest name in the book. 14.1% margin and 62% top-3 concentration mean this is a development target, not a live underwriting. No documents on file.",
    attention_items: ["Not yet contacted", "Intro email overdue"],
  },
  {
    id: "brennan-cole",
    organization_id: ORG,
    name: "Brennan Cole",
    location_city: "Nashville",
    location_state: "TN",
    owner_user_id: PRIYA,
    source: "banker",
    source_detail: "Harris Williams",
    stage: "closing",
    stage_entered_at: "2026-08-15",
    asking_price: 13_200_000,
    expected_purchase_price: 13_200_000,
    probability: 0.9,
    vertical: "legal",
    vertical_metrics: {
      attorney_count: 16,
      partner_count: 5,
      revenue_per_attorney: 443_750,
      revenue_concentration_top3: 0.24,
      practice_area_mix: [
        { name: "Healthcare", share: 0.38 },
        { name: "Corporate", share: 0.31 },
        { name: "Litigation", share: 0.2 },
        { name: "Other", share: 0.11 },
      ],
    },
    flags: [],
    created_at: "2026-03-11T13:00:00.000Z",
    last_activity_at: "2026-08-26T10:15:00.000Z",
    summary:
      "Nashville healthcare/corporate firm in closing. Purchase price $13.2M on $1.9M reported / $2.2M normalized EBITDA (6.0x). Closing checklist is in progress; wire instructions still need confirmation.",
    ai_assessment:
      "Accepted add-backs of $300k (owner compensation and a settled one-time matter) are already in the SPA schedule. Confirmatory is complete. Remaining work is mechanical: funds flow, bar notices, and lease assignment.",
    attention_items: ["Closing checklist in progress", "Wire instructions unconfirmed"],
  },
  {
    id: "voss-hart",
    organization_id: ORG,
    name: "Voss & Hart",
    location_city: "Seattle",
    location_state: "WA",
    owner_user_id: MARCUS,
    source: "proprietary",
    source_detail: "Alex network",
    stage: "passed",
    stage_entered_at: "2026-06-12",
    asking_price: 18_000_000,
    expected_purchase_price: 18_000_000,
    probability: 0,
    vertical: "legal",
    vertical_metrics: {
      attorney_count: 19,
      partner_count: 5,
      revenue_per_attorney: 463_158,
      revenue_concentration_top2: 0.61,
      revenue_concentration_top3: 0.68,
      practice_area_mix: [
        { name: "Litigation", share: 0.71 },
        { name: "Corporate", share: 0.18 },
        { name: "Other", share: 0.11 },
      ],
    },
    flags: ["concentration", "declining_book"],
    created_at: "2026-04-02T10:00:00.000Z",
    last_activity_at: "2026-06-12T16:00:00.000Z",
    summary:
      "Passed 12 Jun. Seattle litigation shop with $8.8M revenue. Top-two attorneys represent 61% of collections and the litigation book declined year over year. Kept in the system as a negative case.",
    ai_assessment:
      "Revenue fell from $9.1M to $8.8M and EBITDA from $2.1M to $1.8M. Combined with 61% top-two concentration, the book failed Northline's key-person screen. Do not reopen without a material change in origination mix.",
    attention_items: [],
  },
  {
    id: "ellison-pike",
    organization_id: ORG,
    name: "Ellison Pike",
    location_city: "New York",
    location_state: "NY",
    owner_user_id: ALEX,
    source: "counsel_intro",
    source_detail: "Cravath intro",
    stage: "closed",
    stage_entered_at: "2026-05-15",
    asking_price: 24_000_000,
    expected_purchase_price: 24_000_000,
    probability: 1,
    vertical: "legal",
    vertical_metrics: {
      attorney_count: 24,
      partner_count: 7,
      revenue_per_attorney: 508_333,
      revenue_concentration_top3: 0.21,
      practice_area_mix: [
        { name: "Corporate", share: 0.52 },
        { name: "Litigation", share: 0.28 },
        { name: "Other", share: 0.2 },
      ],
    },
    flags: [],
    created_at: "2025-09-18T12:00:00.000Z",
    last_activity_at: "2026-05-30T18:00:00.000Z",
    summary:
      "Closed 15 May. New York corporate platform acquired at $24.0M on $3.2M reported / $3.6M normalized EBITDA. Lives in the book so Closed is a first-class stage, not an archive.",
    ai_assessment:
      "Acquisition complete. TTM-at-close revenue $12.2M. Integration is outside this workspace; figures here are the signed quality-of-earnings pack.",
    attention_items: [],
  },
];

export function portfolioSlice(): ReturnType<typeof emptyRelated> {
  const whitakerFy23 = buildPeriod({
    id: "wd_fy2023",
    dealId: "whitaker-dunn",
    label: "FY2023",
    type: "fiscal_year",
    start: "2023-01-01",
    end: "2023-12-31",
    latest: false,
    order: 1,
    revenue: 4_850_000,
    direct: 1_358_000,
    opex: 2_492_000,
    ebitda: 1_000_000,
  });
  const whitakerFy24 = buildPeriod({
    id: "wd_fy2024",
    dealId: "whitaker-dunn",
    label: "FY2024",
    type: "fiscal_year",
    start: "2024-01-01",
    end: "2024-12-31",
    latest: true,
    order: 2,
    revenue: 5_200_000,
    direct: 1_456_000,
    opex: 2_644_000,
    ebitda: 1_100_000,
  });

  const millerFy23 = buildPeriod({
    id: "ml_fy2023",
    dealId: "miller-law",
    label: "FY2023",
    type: "fiscal_year",
    start: "2023-01-01",
    end: "2023-12-31",
    latest: false,
    order: 1,
    revenue: 10_600_000,
    direct: 2_968_000,
    opex: 5_132_000,
    ebitda: 2_500_000,
  });
  const millerFy24 = buildPeriod({
    id: "ml_fy2024",
    dealId: "miller-law",
    label: "FY2024",
    type: "fiscal_year",
    start: "2024-01-01",
    end: "2024-12-31",
    latest: true,
    order: 2,
    revenue: 11_400_000,
    direct: 3_192_000,
    opex: 5_408_000,
    ebitda: 2_800_000,
  });

  const rhodes = buildPeriod({
    id: "rp_fy2024",
    dealId: "rhodes-pell",
    label: "FY2024",
    type: "fiscal_year",
    start: "2024-01-01",
    end: "2024-12-31",
    latest: true,
    order: 1,
    revenue: 6_800_000,
    direct: 1_904_000,
    opex: 3_296_000,
    ebitda: 1_600_000,
  });

  const sato = buildPeriod({
    id: "sb_fy2024",
    dealId: "sato-barrett",
    label: "FY2024",
    type: "fiscal_year",
    start: "2024-01-01",
    end: "2024-12-31",
    latest: true,
    order: 1,
    revenue: 4_100_000,
    direct: 1_230_000,
    opex: 2_150_000,
    ebitda: 720_000,
  });

  const quinn = buildPeriod({
    id: "qh_fy2024",
    dealId: "quinn-harbor",
    label: "FY2024",
    type: "fiscal_year",
    start: "2024-01-01",
    end: "2024-12-31",
    latest: true,
    order: 1,
    revenue: 9_600_000,
    direct: 2_688_000,
    opex: 4_712_000,
    ebitda: 2_200_000,
  });

  const keller = buildPeriod({
    id: "kf_fy2024",
    dealId: "keller-frost",
    label: "FY2024",
    type: "fiscal_year",
    start: "2024-01-01",
    end: "2024-12-31",
    latest: true,
    order: 1,
    revenue: 3_400_000,
    direct: 1_020_000,
    opex: 1_800_000,
    ebitda: 580_000,
  });

  const ortiz = buildPeriod({
    id: "ol_fy2024",
    dealId: "ortiz-lang",
    label: "FY2024",
    type: "fiscal_year",
    start: "2024-01-01",
    end: "2024-12-31",
    latest: true,
    order: 1,
    revenue: 2_900_000,
    direct: 870_000,
    opex: 1_620_000,
    ebitda: 410_000,
  });

  const brennanFy23 = buildPeriod({
    id: "bc_fy2023",
    dealId: "brennan-cole",
    label: "FY2023",
    type: "fiscal_year",
    start: "2023-01-01",
    end: "2023-12-31",
    latest: false,
    order: 1,
    revenue: 6_650_000,
    direct: 1_862_000,
    opex: 3_088_000,
    ebitda: 1_700_000,
  });
  const brennanFy24 = buildPeriod({
    id: "bc_fy2024",
    dealId: "brennan-cole",
    label: "FY2024",
    type: "fiscal_year",
    start: "2024-01-01",
    end: "2024-12-31",
    latest: true,
    order: 2,
    revenue: 7_100_000,
    direct: 1_988_000,
    opex: 3_212_000,
    ebitda: 1_900_000,
  });

  const vossFy23 = buildPeriod({
    id: "vh_fy2023",
    dealId: "voss-hart",
    label: "FY2023",
    type: "fiscal_year",
    start: "2023-01-01",
    end: "2023-12-31",
    latest: false,
    order: 1,
    revenue: 9_100_000,
    direct: 2_548_000,
    opex: 4_452_000,
    ebitda: 2_100_000,
  });
  const vossFy24 = buildPeriod({
    id: "vh_fy2024",
    dealId: "voss-hart",
    label: "FY2024",
    type: "fiscal_year",
    start: "2024-01-01",
    end: "2024-12-31",
    latest: true,
    order: 2,
    revenue: 8_800_000,
    direct: 2_464_000,
    opex: 4_536_000,
    ebitda: 1_800_000,
  });

  const ellison = buildPeriod({
    id: "ep_fy2024",
    dealId: "ellison-pike",
    label: "FY2024",
    type: "fiscal_year",
    start: "2024-01-01",
    end: "2024-12-31",
    latest: true,
    order: 1,
    revenue: 12_200_000,
    direct: 3_416_000,
    opex: 5_584_000,
    ebitda: 3_200_000,
  });

  return merge(
    {
      ...emptyRelated(),
      contacts: [
        contact({
          id: "con_wd",
          deal_id: "whitaker-dunn",
          name: "Lauren Whitaker",
          title: "Managing Partner",
          email: "lwhitaker@whitakerdunn.com",
          phone: "+1 404 555 0190",
          is_primary: true,
        }),
        contact({
          id: "con_ml",
          deal_id: "miller-law",
          name: "David Miller",
          title: "Managing Partner",
          email: "dmiller@millerlaw.com",
          phone: "+1 214 555 0166",
          is_primary: true,
        }),
        contact({
          id: "con_ml_cfo",
          deal_id: "miller-law",
          name: "Anita Brooks",
          title: "Controller",
          email: "abrooks@millerlaw.com",
          phone: "+1 214 555 0167",
          is_primary: false,
        }),
        contact({
          id: "con_rp",
          deal_id: "rhodes-pell",
          name: "Hannah Rhodes",
          title: "Managing Partner",
          email: "hrhodes@rhodespell.com",
          phone: "+1 303 555 0122",
          is_primary: true,
        }),
        contact({
          id: "con_sb",
          deal_id: "sato-barrett",
          name: "Kenji Sato",
          title: "Managing Partner",
          email: "ksato@satobarrett.com",
          phone: "+1 310 555 0177",
          is_primary: true,
        }),
        contact({
          id: "con_qh",
          deal_id: "quinn-harbor",
          name: "Margaret Quinn",
          title: "Managing Partner",
          email: "mquinn@quinnharbor.com",
          phone: "+1 617 555 0133",
          is_primary: true,
        }),
        contact({
          id: "con_kf",
          deal_id: "keller-frost",
          name: "Pat Keller",
          title: "Founding Partner",
          email: "pkeller@kellerfrost.com",
          phone: "+1 612 555 0181",
          is_primary: true,
        }),
        contact({
          id: "con_ol",
          deal_id: "ortiz-lang",
          name: "Marisol Ortiz",
          title: "Managing Partner",
          email: "mortiz@ortizlang.com",
          phone: "+1 602 555 0148",
          is_primary: true,
        }),
        contact({
          id: "con_bc",
          deal_id: "brennan-cole",
          name: "James Brennan",
          title: "Managing Partner",
          email: "jbrennan@brennancole.com",
          phone: "+1 615 555 0104",
          is_primary: true,
        }),
        contact({
          id: "con_vh",
          deal_id: "voss-hart",
          name: "Erik Voss",
          title: "Managing Partner",
          email: "evoss@vosshart.com",
          phone: "+1 206 555 0199",
          is_primary: true,
        }),
        contact({
          id: "con_ep",
          deal_id: "ellison-pike",
          name: "Helen Ellison",
          title: "Managing Partner",
          email: "hellison@ellisonpike.com",
          phone: "+1 212 555 0120",
          is_primary: true,
        }),
      ],
      financial_periods: [
        whitakerFy23.period,
        whitakerFy24.period,
        millerFy23.period,
        millerFy24.period,
        rhodes.period,
        sato.period,
        quinn.period,
        keller.period,
        ortiz.period,
        brennanFy23.period,
        brennanFy24.period,
        vossFy23.period,
        vossFy24.period,
        ellison.period,
      ],
      financial_metrics: [
        ...whitakerFy23.metrics,
        ...whitakerFy24.metrics,
        ...millerFy23.metrics,
        ...millerFy24.metrics,
        ...rhodes.metrics,
        ...sato.metrics,
        ...quinn.metrics,
        ...keller.metrics,
        ...ortiz.metrics,
        ...brennanFy23.metrics,
        ...brennanFy24.metrics,
        ...vossFy23.metrics,
        ...vossFy24.metrics,
        ...ellison.metrics,
      ],
      ebitda_adjustments: [
        adj({
          id: "adj_wd_occ",
          dealId: "whitaker-dunn",
          periodId: "wd_fy2024",
          category: "occupancy",
          description: "Above-market Midtown lease",
          amount: 80_000,
          source: "Lease vs Atlanta Class B comps",
          origin: "ai",
          status: "proposed",
          confidence: 0.68,
          provenance: inference(null, null, "Occupancy", "80000", 0.68),
        }),
        adj({
          id: "adj_ml_owner",
          dealId: "miller-law",
          periodId: "ml_fy2024",
          category: "compensation",
          description: "Owner compensation normalization",
          amount: 150_000,
          source: "Partner draw vs replacement cost",
          origin: "ai",
          status: "accepted",
          confidence: 0.87,
          provenance: fact(
            "doc_ml_pl",
            "Miller_FY2024_PL.pdf",
            "Owner compensation",
            "150000",
            0.87,
            "approved_assumption"
          ),
        }),
        adj({
          id: "adj_rp_onetime",
          dealId: "rhodes-pell",
          periodId: "rp_fy2024",
          category: "one_time",
          description: "Office relocation",
          amount: 75_000,
          source: "One-time moving and build-out",
          origin: "manual",
          status: "accepted",
          provenance: fact(null, null, "One-time", "75000", 0.9, "approved_assumption"),
        }),
        adj({
          id: "adj_bc_owner",
          dealId: "brennan-cole",
          periodId: "bc_fy2024",
          category: "compensation",
          description: "Owner compensation normalization",
          amount: 220_000,
          source: "SPA schedule 3.2",
          origin: "manual",
          status: "accepted",
          provenance: fact(null, "SPA schedule", "Compensation", "220000", 0.95, "approved_assumption"),
        }),
        adj({
          id: "adj_bc_legal",
          dealId: "brennan-cole",
          periodId: "bc_fy2024",
          category: "one_time",
          description: "Settled employment matter",
          amount: 80_000,
          source: "SPA schedule 3.2",
          origin: "manual",
          status: "accepted",
          provenance: fact(null, "SPA schedule", "One-time", "80000", 0.96, "approved_assumption"),
        }),
        adj({
          id: "adj_ep_owner",
          dealId: "ellison-pike",
          periodId: "ep_fy2024",
          category: "compensation",
          description: "Owner compensation normalization",
          amount: 400_000,
          source: "Closed QoE pack",
          origin: "manual",
          status: "accepted",
          provenance: fact(null, "QoE", "Compensation", "400000", 0.99, "approved_assumption"),
        }),
      ],
      documents: [
        doc({
          id: "doc_wd_pl",
          dealId: "whitaker-dunn",
          filename: "Whitaker_Dunn_FY2024_PL.pdf",
          folder: "financials",
          uploadedAt: "2026-08-11T15:00:00.000Z",
          uploadedBy: ELENA,
          classification: "income_statement",
        }),
        doc({
          id: "doc_ml_pl",
          dealId: "miller-law",
          filename: "Miller_FY2024_PL.pdf",
          folder: "financials",
          uploadedAt: "2026-06-20T12:00:00.000Z",
          uploadedBy: PRIYA,
          classification: "income_statement",
        }),
        doc({
          id: "doc_ml_loi",
          dealId: "miller-law",
          filename: "Miller_Law_Signed_LOI.pdf",
          folder: "legal",
          uploadedAt: "2026-07-28T18:00:00.000Z",
          uploadedBy: PRIYA,
          classification: "loi",
        }),
        doc({
          id: "doc_ml_cim",
          dealId: "miller-law",
          filename: "Miller_Law_CIM.pdf",
          folder: "corporate",
          uploadedAt: "2026-05-08T10:00:00.000Z",
          uploadedBy: TOM,
          classification: "cim",
        }),
        doc({
          id: "doc_rp_loi",
          dealId: "rhodes-pell",
          filename: "Rhodes_Pell_Signed_LOI.pdf",
          folder: "legal",
          uploadedAt: "2026-08-06T19:00:00.000Z",
          uploadedBy: ELENA,
          classification: "loi",
        }),
        doc({
          id: "doc_rp_pl",
          dealId: "rhodes-pell",
          filename: "Rhodes_Pell_FY2024_PL.pdf",
          folder: "financials",
          uploadedAt: "2026-07-14T11:00:00.000Z",
          uploadedBy: MARCUS,
        }),
        doc({
          id: "doc_sb_cim",
          dealId: "sato-barrett",
          filename: "Sato_Barrett_CIM.pdf",
          folder: "corporate",
          uploadedAt: "2026-08-18T09:20:00.000Z",
          uploadedBy: MARCUS,
          classification: "cim",
        }),
        doc({
          id: "doc_sb_pl",
          dealId: "sato-barrett",
          filename: "Sato_Barrett_FY2024_PL.pdf",
          folder: "financials",
          uploadedAt: "2026-08-18T09:24:00.000Z",
          uploadedBy: MARCUS,
        }),
        doc({
          id: "doc_qh_cim",
          dealId: "quinn-harbor",
          filename: "Quinn_Harbor_CIM.pdf",
          folder: "corporate",
          uploadedAt: "2026-07-22T13:00:00.000Z",
          uploadedBy: PRIYA,
          classification: "cim",
        }),
        doc({
          id: "doc_qh_nda",
          dealId: "quinn-harbor",
          filename: "Quinn_Harbor_NDA_Draft.docx",
          folder: "legal",
          uploadedAt: "2026-07-24T16:00:00.000Z",
          uploadedBy: ALEX,
          status: "needs_review",
          classification: "nda",
        }),
        doc({
          id: "doc_bc_spa",
          dealId: "brennan-cole",
          filename: "Brennan_Cole_SPA.pdf",
          folder: "legal",
          uploadedAt: "2026-08-15T08:40:00.000Z",
          uploadedBy: PRIYA,
          classification: "purchase_agreement",
        }),
        doc({
          id: "doc_bc_qoe",
          dealId: "brennan-cole",
          filename: "Brennan_Cole_QoE.pdf",
          folder: "financials",
          uploadedAt: "2026-07-30T10:00:00.000Z",
          uploadedBy: MARCUS,
          classification: "qoe_report",
        }),
        doc({
          id: "doc_ep_spa",
          dealId: "ellison-pike",
          filename: "Ellison_Pike_Closing_Binder.pdf",
          folder: "corporate",
          uploadedAt: "2026-05-15T17:00:00.000Z",
          uploadedBy: ALEX,
          classification: "closing_binder",
        }),
      ],
      diligence_requests: [
        req({
          id: "dil_wd_qoe",
          dealId: "whitaker-dunn",
          category: "financial",
          question: "Walk the FY2024 add-backs with Lauren Whitaker.",
          status: "under_review",
          owner: ELENA,
          due: "2026-08-30",
          priority: "high",
        }),
        req({
          id: "dil_wd_wc",
          dealId: "whitaker-dunn",
          category: "financial",
          question: "Monthly working-capital series for FY2024.",
          status: "requested",
          owner: MARCUS,
          due: "2026-09-02",
        }),
        req({
          id: "dil_ml_clients",
          dealId: "miller-law",
          category: "revenue_clients",
          question: "Client list with TTM collections and matter concentration.",
          status: "requested",
          owner: TOM,
          counterparty: "Anita Brooks",
          due: "2026-08-15",
          priority: "critical",
        }),
        req({
          id: "dil_ml_tax",
          dealId: "miller-law",
          category: "tax",
          question: "2025 tax return or filed extension and workpapers.",
          status: "requested",
          owner: MARCUS,
          counterparty: "Anita Brooks",
          due: "2026-08-10",
          priority: "critical",
        }),
        req({
          id: "dil_ml_mal",
          dealId: "miller-law",
          category: "legal",
          question: "Five-year malpractice claims history and carrier loss runs.",
          status: "requested",
          owner: PRIYA,
          counterparty: "David Miller",
          due: "2026-08-20",
          priority: "critical",
        }),
        req({
          id: "dil_ml_pls",
          dealId: "miller-law",
          category: "financial",
          question: "FY2023 and FY2024 P&Ls.",
          status: "complete",
          owner: MARCUS,
          docs: ["doc_ml_pl"],
        }),
        req({
          id: "dil_rp_conf",
          dealId: "rhodes-pell",
          category: "financial",
          question: "Issue confirmatory diligence request list.",
          status: "not_requested",
          owner: PRIYA,
          due: "2026-09-03",
        }),
        req({
          id: "dil_sb_tax",
          dealId: "sato-barrett",
          category: "tax",
          question: "Open tax folder — 2024 and 2025 returns.",
          status: "not_requested",
          owner: MARCUS,
        }),
        req({
          id: "dil_qh_nda",
          dealId: "quinn-harbor",
          category: "legal",
          question: "Return marked NDA from Northline counsel.",
          status: "under_review",
          owner: ALEX,
          due: "2026-08-10",
          priority: "high",
        }),
        req({
          id: "dil_bc_wire",
          dealId: "brennan-cole",
          category: "other",
          question: "Confirm wire instructions and funds-flow memo.",
          status: "follow_up_required",
          owner: PRIYA,
          due: "2026-09-02",
          priority: "critical",
        }),
        req({
          id: "dil_bc_lease",
          dealId: "brennan-cole",
          category: "real_estate",
          question: "Landlord consent to lease assignment.",
          status: "received",
          owner: TOM,
          due: "2026-09-04",
        }),
        req({
          id: "dil_vh_conc",
          dealId: "voss-hart",
          category: "revenue_clients",
          question: "Origination mix for the top two partners.",
          status: "complete",
          owner: MARCUS,
          notes: "Confirmed 61% top-two. Deal passed.",
        }),
      ],
      ai_findings: [],
      tasks: [
        task({
          id: "task_wd_interview",
          dealId: "whitaker-dunn",
          title: "Complete add-back interview",
          owner: ELENA,
          due: "2026-08-30",
        }),
        task({
          id: "task_ml_clients",
          dealId: "miller-law",
          title: "Chase client list from controller",
          owner: TOM,
          due: "2026-08-28",
        }),
        task({
          id: "task_rp_list",
          dealId: "rhodes-pell",
          title: "Kick off confirmatory request list",
          owner: PRIYA,
          due: "2026-09-03",
        }),
        task({
          id: "task_sb_room",
          dealId: "sato-barrett",
          title: "Inventory data room",
          owner: MARCUS,
          due: "2026-09-01",
        }),
        task({
          id: "task_qh_nda",
          dealId: "quinn-harbor",
          title: "Counsel NDA markup",
          owner: ALEX,
          due: "2026-08-10",
        }),
        task({
          id: "task_kf_call",
          dealId: "keller-frost",
          title: "Schedule second call",
          owner: TOM,
          due: "2026-09-04",
        }),
        task({
          id: "task_ol_intro",
          dealId: "ortiz-lang",
          title: "Send intro email",
          owner: ELENA,
          due: "2026-08-01",
        }),
        task({
          id: "task_bc_wire",
          dealId: "brennan-cole",
          title: "Confirm wire instructions",
          owner: PRIYA,
          due: "2026-09-02",
        }),
      ],
      notes: [],
      activities: [
        activity({
          id: "act_wd_pl",
          dealId: "whitaker-dunn",
          actor: ELENA,
          kind: "document_upload",
          title: "Uploaded FY2024 P&L",
          body: "Whitaker_Dunn_FY2024_PL.pdf. Reported EBITDA $1,100,000.",
          at: "2026-08-21T16:00:00.000Z",
        }),
        activity({
          id: "act_ml_chase",
          dealId: "miller-law",
          actor: TOM,
          kind: "diligence_status",
          title: "Chased client list",
          body: "Anita Brooks confirmed she would send the client list this week. Still outstanding.",
          at: "2026-08-25T19:10:00.000Z",
        }),
        activity({
          id: "act_ml_loi",
          dealId: "miller-law",
          actor: PRIYA,
          kind: "stage_change",
          title: "Moved to Confirmatory Diligence",
          body: "LOI signed. Confirmatory request list issued.",
          at: "2026-07-28T18:10:00.000Z",
        }),
        activity({
          id: "act_rp_loi",
          dealId: "rhodes-pell",
          actor: ELENA,
          kind: "stage_change",
          title: "LOI signed",
          body: "$11.2M signed LOI. Confirmatory not started.",
          at: "2026-08-06T19:05:00.000Z",
        }),
        activity({
          id: "act_sb_room",
          dealId: "sato-barrett",
          actor: MARCUS,
          kind: "document_upload",
          title: "Data room opened",
          body: "CIM and FY2024 P&L uploaded. Room otherwise empty.",
          at: "2026-08-22T11:00:00.000Z",
        }),
        activity({
          id: "act_qh_nda",
          dealId: "quinn-harbor",
          actor: ALEX,
          kind: "document_status",
          title: "NDA sent to counsel",
          body: "Raymond James draft in review. No movement since 8 Aug.",
          at: "2026-08-08T12:00:00.000Z",
        }),
        activity({
          id: "act_kf_call",
          dealId: "keller-frost",
          actor: TOM,
          kind: "note",
          title: "First call with Pat Keller",
          body: "Introductory conversation. Pat is willing to share a P&L after a second call.",
          at: "2026-08-20T17:45:00.000Z",
        }),
        activity({
          id: "act_ol_add",
          dealId: "ortiz-lang",
          actor: TOM,
          kind: "system",
          title: "Target added from ABA notes",
          body: "No outreach yet.",
          at: "2026-07-18T09:30:00.000Z",
        }),
        activity({
          id: "act_bc_close",
          dealId: "brennan-cole",
          actor: PRIYA,
          kind: "stage_change",
          title: "Moved to Closing",
          body: "Confirmatory complete. Closing checklist opened.",
          at: "2026-08-15T08:50:00.000Z",
        }),
        activity({
          id: "act_bc_checklist",
          dealId: "brennan-cole",
          actor: PRIYA,
          kind: "note",
          title: "Closing checklist updated",
          body: "Funds flow still missing final wire instructions.",
          at: "2026-08-26T10:15:00.000Z",
        }),
        activity({
          id: "act_vh_pass",
          dealId: "voss-hart",
          actor: ALEX,
          kind: "stage_change",
          title: "Passed",
          body: "Top-two concentration 61% and declining litigation book.",
          at: "2026-06-12T16:00:00.000Z",
        }),
        activity({
          id: "act_ep_close",
          dealId: "ellison-pike",
          actor: ALEX,
          kind: "stage_change",
          title: "Closed",
          body: "Acquired at $24.0M.",
          at: "2026-05-15T17:05:00.000Z",
        }),
      ],
      audit_events: [
        {
          id: "aud_ml_stage",
          organization_id: ORG,
          deal_id: "miller-law",
          actor_user_id: PRIYA,
          entity_type: "deal",
          entity_id: "miller-law",
          action: "stage_change",
          before: { stage: "loi" },
          after: { stage: "confirmatory_diligence" },
          occurred_at: "2026-07-28T18:10:00.000Z",
        },
      ],
    }
  );
}
