import { CURRENT_ORG_ID } from "./constants";
import { doc } from "./seed-helpers";
import type {
  Assumption,
  CommunicationInterpretation,
  Conflict,
  DocumentRecord,
  DocumentVersion,
  EvidenceItem,
  EvidenceTables,
  ExtractedFact,
  Extraction,
  MissingItem,
  NegotiationPosition,
  Recommendation,
  ReconciliationCheck,
  UnderwritingRisk,
  ValuationFactor,
  ValuationScenario,
} from "./types";

const ORG = CURRENT_ORG_ID;
const DEAL = "hale-mercer";
const ELENA = "user_elena";
const MARCUS = "user_marcus";
const PRIYA = "user_priya";
const TOM = "user_tom";
const ENTITY = "Hale & Mercer LLP";

function ev(partial: Omit<EvidenceItem, "organization_id">): EvidenceItem {
  return { organization_id: ORG, ...partial };
}

function fact(partial: Omit<ExtractedFact, "organization_id">): ExtractedFact {
  return { organization_id: ORG, ...partial };
}

export function haleMessyDocuments(): DocumentRecord[] {
  return [
    doc({
      id: "doc_hale_tax_2022",
      dealId: DEAL,
      filename: "Tax Return 2022.pdf",
      folder: "tax",
      uploadedAt: "2026-07-22T11:00:00.000Z",
      uploadedBy: TOM,
      classification: "tax_return",
      pages: 38,
      payload: { year: 2022, revenue_cash: 7_050_000, form: "1065" },
    }),
    doc({
      id: "doc_hale_tax_2023",
      dealId: DEAL,
      filename: "Tax Return 2023.pdf",
      folder: "tax",
      uploadedAt: "2026-07-22T11:02:00.000Z",
      uploadedBy: TOM,
      classification: "tax_return",
      pages: 41,
      payload: { year: 2023, revenue_cash: 7_180_000, form: "1065" },
      linked: ["dil_hale_tax_2024"],
    }),
    doc({
      id: "doc_hale_tax_2024_messy",
      dealId: DEAL,
      filename: "Tax Return 2024.pdf",
      folder: "tax",
      uploadedAt: "2026-07-22T11:06:00.000Z",
      uploadedBy: TOM,
      classification: "tax_return",
      pages: 44,
      payload: { year: 2024, revenue_cash: 7_480_000, form: "1065" },
      linked: ["dil_hale_tax_2024"],
    }),
    doc({
      id: "doc_hale_pl_2023_xlsx",
      dealId: DEAL,
      filename: "P&L 2023.xlsx",
      folder: "financials",
      uploadedAt: "2026-07-19T09:10:00.000Z",
      uploadedBy: TOM,
      classification: "income_statement",
      pages: 1,
      payload: { period: "FY2023", revenue: 7_370_000, ebitda: 1_700_000 },
      linked: ["dil_hale_pls"],
    }),
    doc({
      id: "doc_hale_pl_2024_final",
      dealId: DEAL,
      filename: "P&L 2024 FINAL.xlsx",
      folder: "financials",
      uploadedAt: "2026-07-19T09:14:00.000Z",
      uploadedBy: TOM,
      classification: "income_statement",
      pages: 1,
      payload: { period: "FY2024", revenue: 7_695_000, ebitda: 1_875_000, superseded: true },
      status: "needs_review",
      confidence: 0.71,
    }),
    doc({
      id: "doc_hale_pl_2024_updated",
      dealId: DEAL,
      filename: "P&L 2024 FINAL UPDATED.xlsx",
      folder: "financials",
      uploadedAt: "2026-07-28T16:40:00.000Z",
      uploadedBy: MARCUS,
      classification: "income_statement",
      pages: 1,
      payload: { period: "FY2024", revenue: 7_720_000, ebitda: 1_900_000, supersedes: "P&L 2024 FINAL.xlsx" },
      linked: ["dil_hale_pls"],
    }),
    doc({
      id: "doc_hale_qb",
      dealId: DEAL,
      filename: "QB export jan-june.xlsx",
      folder: "financials",
      uploadedAt: "2026-08-09T10:20:00.000Z",
      uploadedBy: MARCUS,
      classification: "quickbooks_monthly",
      pages: 1,
      payload: { period: "H1 2025", revenue: 4_050_000, ebitda: 980_000 },
      status: "needs_review",
      confidence: 0.74,
      linked: ["dil_hale_monthly"],
    }),
    doc({
      id: "doc_hale_gl_export",
      dealId: DEAL,
      filename: "GL_export.xlsx",
      folder: "financials",
      uploadedAt: "2026-08-11T18:50:00.000Z",
      uploadedBy: MARCUS,
      classification: "general_ledger",
      pages: 1,
      payload: { professional_services_ttm: 248_000 },
      linked: ["dil_hale_ps"],
    }),
    doc({
      id: "doc_hale_payroll_v2",
      dealId: DEAL,
      filename: "Payroll Detail v2.xlsx",
      folder: "payroll",
      uploadedAt: "2026-08-08T13:30:00.000Z",
      uploadedBy: MARCUS,
      classification: "payroll_register",
      pages: 1,
      payload: { partner_draws: 980_000, owner_not_separated: true },
      status: "needs_review",
      confidence: 0.76,
      linked: ["dil_hale_payroll"],
    }),
    doc({
      id: "doc_hale_prod_old",
      dealId: DEAL,
      filename: "Attorney Production.xlsx",
      folder: "attorney_production",
      uploadedAt: "2026-08-20T11:00:00.000Z",
      uploadedBy: TOM,
      classification: "attorney_production",
      pages: 3,
      payload: { collections: 7_980_000, superseded: true },
      status: "needs_review",
      confidence: 0.7,
    }),
    doc({
      id: "doc_hale_prod_new",
      dealId: DEAL,
      filename: "Attorney Production NEW.xlsx",
      folder: "attorney_production",
      uploadedAt: "2026-08-22T15:20:00.000Z",
      uploadedBy: TOM,
      classification: "attorney_production",
      pages: 4,
      payload: { collections: 8_150_000, top_attorney: "Daniel Mercer", share: 0.17 },
      linked: ["dil_hale_production"],
    }),
    doc({
      id: "doc_hale_client_rev",
      dealId: DEAL,
      filename: "Client Matter Revenue.xlsx",
      folder: "client_matter",
      uploadedAt: "2026-08-16T14:05:00.000Z",
      uploadedBy: ELENA,
      classification: "client_matter_revenue",
      pages: 1,
      payload: { billed: 8_280_000, collected_ttm: 8_400_000 },
      linked: ["dil_hale_clients"],
    }),
    doc({
      id: "doc_hale_ar_aging",
      dealId: DEAL,
      filename: "AR Aging.xlsx",
      folder: "financials",
      uploadedAt: "2026-08-17T09:40:00.000Z",
      uploadedBy: MARCUS,
      classification: "ar_aging",
      pages: 1,
      payload: { ar_total: 1_120_000 },
      linked: ["dil_hale_ar"],
    }),
    doc({
      id: "doc_hale_lease_messy",
      dealId: DEAL,
      filename: "Lease.pdf",
      folder: "real_estate",
      uploadedAt: "2026-07-29T10:05:00.000Z",
      uploadedBy: TOM,
      classification: "office_lease",
      pages: 42,
      payload: { address: "333 W Wacker, Chicago", expiry: "2028-04-30", rent: 540_000 },
      linked: ["dil_hale_lease"],
    }),
    doc({
      id: "doc_hale_org_messy",
      dealId: DEAL,
      filename: "Org Chart.pdf",
      folder: "corporate",
      uploadedAt: "2026-07-21T12:50:00.000Z",
      uploadedBy: TOM,
      classification: "org_chart",
      pages: 2,
      linked: ["dil_hale_org"],
    }),
    doc({
      id: "doc_hale_nda_messy",
      dealId: DEAL,
      filename: "NDA executed.pdf",
      folder: "legal",
      uploadedAt: "2026-06-20T09:40:00.000Z",
      uploadedBy: ELENA,
      classification: "nda",
      pages: 7,
      linked: ["dil_hale_nda"],
    }),
    doc({
      id: "doc_hale_loi",
      dealId: DEAL,
      filename: "Indication_or_LOI.pdf",
      folder: "legal",
      uploadedAt: "2026-08-03T16:00:00.000Z",
      uploadedBy: ELENA,
      classification: "indication",
      pages: 6,
      payload: { seller_ask: 16_800_000, multiple_on_pf: 6.2 },
    }),
    doc({
      id: "doc_hale_email_ps",
      dealId: DEAL,
      filename: "RE professional services expenses.eml",
      folder: "other",
      uploadedAt: "2026-08-25T15:10:00.000Z",
      uploadedBy: ELENA,
      classification: "email",
      pages: 1,
      payload: { explains: 40_000, of_unexplained: 180_000 },
      linked: ["dil_hale_ps"],
    }),
    doc({
      id: "doc_hale_email_lease",
      dealId: DEAL,
      filename: "Re office lease 333 W Wacker.eml",
      folder: "other",
      uploadedAt: "2026-08-24T19:20:00.000Z",
      uploadedBy: PRIYA,
      classification: "email",
      pages: 1,
      linked: ["dil_hale_lease"],
    }),
    doc({
      id: "doc_hale_note_retention",
      dealId: DEAL,
      filename: "Partner retention discussion.md",
      folder: "other",
      uploadedAt: "2026-08-25T21:00:00.000Z",
      uploadedBy: ELENA,
      classification: "meeting_note",
      pages: 1,
      linked: ["dil_hale_employment"],
    }),
    doc({
      id: "doc_hale_note_occupancy",
      dealId: DEAL,
      filename: "Occupancy and expenses post-close.md",
      folder: "other",
      uploadedAt: "2026-08-26T18:15:00.000Z",
      uploadedBy: MARCUS,
      classification: "meeting_note",
      pages: 1,
      linked: ["dil_hale_lease"],
    }),
  ];
}

function items(): EvidenceItem[] {
  return [
    ev({
      id: "ev_hale_tax_2022",
      deal_id: DEAL,
      kind: "document",
      document_id: "doc_hale_tax_2022",
      filename: "Tax Return 2022.pdf",
      title: "Tax Return 2022",
      detected_type: "tax_return",
      detected_period: "FY2022",
      detected_entity: ENTITY,
      file_format: "pdf",
      processing_status: "analyzed",
      confidence: 0.95,
      potential_duplicate_of: null,
      superseded_by_id: null,
      supersedes_id: null,
      human_review_status: "unreviewed",
      source_system: "data_room",
      external_item_id: null,
      external_thread_id: null,
      external_meeting_id: null,
      author: null,
      sender: null,
      participants: [],
      occurred_at: "2023-03-15T12:00:00.000Z",
      ingested_at: "2026-07-22T11:00:00.000Z",
      last_synchronized_at: null,
      subject: null,
      body: null,
      snippet: "Form 1065 — cash receipts $7,050,000",
      page_count: 38,
      mime_type: "application/pdf",
      size_bytes: 1_840_000,
    }),
    ev({
      id: "ev_hale_tax_2023",
      deal_id: DEAL,
      kind: "document",
      document_id: "doc_hale_tax_2023",
      filename: "Tax Return 2023.pdf",
      title: "Tax Return 2023",
      detected_type: "tax_return",
      detected_period: "FY2023",
      detected_entity: ENTITY,
      file_format: "pdf",
      processing_status: "analyzed",
      confidence: 0.95,
      potential_duplicate_of: null,
      superseded_by_id: null,
      supersedes_id: null,
      human_review_status: "unreviewed",
      source_system: "data_room",
      external_item_id: null,
      external_thread_id: null,
      external_meeting_id: null,
      author: null,
      sender: null,
      participants: [],
      occurred_at: "2024-03-12T12:00:00.000Z",
      ingested_at: "2026-07-22T11:02:00.000Z",
      last_synchronized_at: null,
      subject: null,
      body: null,
      snippet: "Form 1065 — cash receipts $7,180,000",
      page_count: 41,
      mime_type: "application/pdf",
      size_bytes: 1_920_000,
    }),
    ev({
      id: "ev_hale_tax_2024",
      deal_id: DEAL,
      kind: "document",
      document_id: "doc_hale_tax_2024_messy",
      filename: "Tax Return 2024.pdf",
      title: "Tax Return 2024",
      detected_type: "tax_return",
      detected_period: "FY2024",
      detected_entity: ENTITY,
      file_format: "pdf",
      processing_status: "analyzed",
      confidence: 0.94,
      potential_duplicate_of: "ev_hale_tax_1065",
      superseded_by_id: null,
      supersedes_id: null,
      human_review_status: "unreviewed",
      source_system: "data_room",
      external_item_id: null,
      external_thread_id: null,
      external_meeting_id: null,
      author: null,
      sender: null,
      participants: [],
      occurred_at: "2025-03-18T12:00:00.000Z",
      ingested_at: "2026-07-22T11:06:00.000Z",
      last_synchronized_at: null,
      subject: null,
      body: null,
      snippet: "Form 1065 — cash receipts $7,480,000 vs accrual P&L $7,720,000",
      page_count: 44,
      mime_type: "application/pdf",
      size_bytes: 2_040_000,
    }),
    ev({
      id: "ev_hale_tax_1065",
      deal_id: DEAL,
      kind: "document",
      document_id: "doc_hale_tax_2024",
      filename: "Hale_Mercer_2024_Form_1065.pdf",
      title: "2024 Form 1065 (clean copy)",
      detected_type: "tax_return",
      detected_period: "FY2024",
      detected_entity: ENTITY,
      file_format: "pdf",
      processing_status: "analyzed",
      confidence: 0.9,
      potential_duplicate_of: "ev_hale_tax_2024",
      superseded_by_id: null,
      supersedes_id: null,
      human_review_status: "confirmed",
      source_system: "data_room",
      external_item_id: null,
      external_thread_id: null,
      external_meeting_id: null,
      author: null,
      sender: null,
      participants: [],
      occurred_at: "2025-03-18T12:00:00.000Z",
      ingested_at: "2026-07-22T11:05:00.000Z",
      last_synchronized_at: null,
      subject: null,
      body: null,
      snippet: "Same 2024 return; banker-renamed copy",
      page_count: 46,
      mime_type: "application/pdf",
      size_bytes: 2_100_000,
    }),
    ev({
      id: "ev_hale_pl_2023",
      deal_id: DEAL,
      kind: "document",
      document_id: "doc_hale_pl_2023_xlsx",
      filename: "P&L 2023.xlsx",
      title: "P&L 2023",
      detected_type: "pnl",
      detected_period: "FY2023",
      detected_entity: ENTITY,
      file_format: "xlsx",
      processing_status: "analyzed",
      confidence: 0.96,
      potential_duplicate_of: "ev_hale_fy23_pl_pdf",
      superseded_by_id: null,
      supersedes_id: null,
      human_review_status: "confirmed",
      source_system: "data_room",
      external_item_id: null,
      external_thread_id: null,
      external_meeting_id: null,
      author: null,
      sender: null,
      participants: [],
      occurred_at: "2024-01-20T12:00:00.000Z",
      ingested_at: "2026-07-19T09:10:00.000Z",
      last_synchronized_at: null,
      subject: null,
      body: null,
      snippet: "Revenue $7,370,000 · EBITDA $1,700,000",
      page_count: 1,
      mime_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      size_bytes: 88_000,
    }),
    ev({
      id: "ev_hale_fy23_pl_pdf",
      deal_id: DEAL,
      kind: "document",
      document_id: "doc_hale_fy23_pl",
      filename: "Hale_Mercer_FY2023_PL.pdf",
      title: "FY2023 P&L (PDF)",
      detected_type: "pnl",
      detected_period: "FY2023",
      detected_entity: ENTITY,
      file_format: "pdf",
      processing_status: "analyzed",
      confidence: 0.94,
      potential_duplicate_of: "ev_hale_pl_2023",
      superseded_by_id: null,
      supersedes_id: null,
      human_review_status: "confirmed",
      source_system: "data_room",
      external_item_id: null,
      external_thread_id: null,
      external_meeting_id: null,
      author: null,
      sender: null,
      participants: [],
      occurred_at: "2024-01-20T12:00:00.000Z",
      ingested_at: "2026-07-18T14:10:00.000Z",
      last_synchronized_at: null,
      subject: null,
      body: null,
      snippet: "Same FY2023 numbers as the xlsx",
      page_count: 8,
      mime_type: "application/pdf",
      size_bytes: 240_000,
    }),
    ev({
      id: "ev_hale_pl_2024_final",
      deal_id: DEAL,
      kind: "document",
      document_id: "doc_hale_pl_2024_final",
      filename: "P&L 2024 FINAL.xlsx",
      title: "P&L 2024 FINAL",
      detected_type: "pnl",
      detected_period: "FY2024",
      detected_entity: ENTITY,
      file_format: "xlsx",
      processing_status: "analyzed",
      confidence: 0.88,
      potential_duplicate_of: "ev_hale_pl_2024_updated",
      superseded_by_id: "ev_hale_pl_2024_updated",
      supersedes_id: null,
      human_review_status: "unreviewed",
      source_system: "data_room",
      external_item_id: null,
      external_thread_id: null,
      external_meeting_id: null,
      author: null,
      sender: null,
      participants: [],
      occurred_at: "2025-01-18T12:00:00.000Z",
      ingested_at: "2026-07-19T09:14:00.000Z",
      last_synchronized_at: null,
      subject: null,
      body: null,
      snippet: "Revenue $7,695,000 · EBITDA $1,875,000 — superseded",
      page_count: 1,
      mime_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      size_bytes: 92_000,
    }),
    ev({
      id: "ev_hale_pl_2024_updated",
      deal_id: DEAL,
      kind: "document",
      document_id: "doc_hale_pl_2024_updated",
      filename: "P&L 2024 FINAL UPDATED.xlsx",
      title: "P&L 2024 FINAL UPDATED",
      detected_type: "pnl",
      detected_period: "FY2024",
      detected_entity: ENTITY,
      file_format: "xlsx",
      processing_status: "analyzed",
      confidence: 0.97,
      potential_duplicate_of: "ev_hale_pl_2024_final",
      superseded_by_id: null,
      supersedes_id: "ev_hale_pl_2024_final",
      human_review_status: "confirmed",
      source_system: "data_room",
      external_item_id: null,
      external_thread_id: null,
      external_meeting_id: null,
      author: null,
      sender: null,
      participants: [],
      occurred_at: "2025-02-04T12:00:00.000Z",
      ingested_at: "2026-07-28T16:40:00.000Z",
      last_synchronized_at: null,
      subject: null,
      body: null,
      snippet: "Revenue $7,720,000 · EBITDA $1,900,000 — current",
      page_count: 1,
      mime_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      size_bytes: 96_000,
    }),
    ev({
      id: "ev_hale_ttm_pl",
      deal_id: DEAL,
      kind: "document",
      document_id: "doc_hale_ttm_pl",
      filename: "Hale_Mercer_TTM_2025_PL.pdf",
      title: "TTM 2025 P&L",
      detected_type: "pnl",
      detected_period: "TTM 2025",
      detected_entity: ENTITY,
      file_format: "pdf",
      processing_status: "analyzed",
      confidence: 0.97,
      potential_duplicate_of: null,
      superseded_by_id: null,
      supersedes_id: null,
      human_review_status: "confirmed",
      source_system: "data_room",
      external_item_id: null,
      external_thread_id: null,
      external_meeting_id: null,
      author: null,
      sender: null,
      participants: [],
      occurred_at: "2025-07-08T12:00:00.000Z",
      ingested_at: "2026-08-05T16:40:00.000Z",
      last_synchronized_at: null,
      subject: null,
      body: null,
      snippet: "Revenue $8,400,000 · EBITDA $2,100,000 · owner comp $1,420,000",
      page_count: 11,
      mime_type: "application/pdf",
      size_bytes: 310_000,
    }),
    ev({
      id: "ev_hale_qb",
      deal_id: DEAL,
      kind: "document",
      document_id: "doc_hale_qb",
      filename: "QB export jan-june.xlsx",
      title: "QuickBooks monthly export (Jan–June)",
      detected_type: "pnl",
      detected_period: "H1 2025",
      detected_entity: ENTITY,
      file_format: "xlsx",
      processing_status: "analyzed",
      confidence: 0.81,
      potential_duplicate_of: null,
      superseded_by_id: null,
      supersedes_id: null,
      human_review_status: "unreviewed",
      source_system: "data_room",
      external_item_id: null,
      external_thread_id: null,
      external_meeting_id: null,
      author: "Claire Hoffman",
      sender: null,
      participants: [],
      occurred_at: "2025-07-02T12:00:00.000Z",
      ingested_at: "2026-08-09T10:20:00.000Z",
      last_synchronized_at: null,
      subject: null,
      body: null,
      snippet: "Six months sum to $4,050,000 revenue — not half of TTM",
      page_count: 1,
      mime_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      size_bytes: 140_000,
    }),
    ev({
      id: "ev_hale_gl",
      deal_id: DEAL,
      kind: "document",
      document_id: "doc_hale_gl_export",
      filename: "GL_export.xlsx",
      title: "GL export",
      detected_type: "gl",
      detected_period: "TTM 2025",
      detected_entity: ENTITY,
      file_format: "xlsx",
      processing_status: "analyzed",
      confidence: 0.86,
      potential_duplicate_of: null,
      superseded_by_id: null,
      supersedes_id: null,
      human_review_status: "unreviewed",
      source_system: "data_room",
      external_item_id: null,
      external_thread_id: null,
      external_meeting_id: null,
      author: null,
      sender: null,
      participants: [],
      occurred_at: "2025-07-10T12:00:00.000Z",
      ingested_at: "2026-08-11T18:50:00.000Z",
      last_synchronized_at: null,
      subject: null,
      body: null,
      snippet: "Professional services TTM $248,000",
      page_count: 1,
      mime_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      size_bytes: 420_000,
    }),
    ev({
      id: "ev_hale_payroll_v2",
      deal_id: DEAL,
      kind: "document",
      document_id: "doc_hale_payroll_v2",
      filename: "Payroll Detail v2.xlsx",
      title: "Payroll Detail v2",
      detected_type: "payroll_register",
      detected_period: "TTM 2025",
      detected_entity: ENTITY,
      file_format: "xlsx",
      processing_status: "analyzed",
      confidence: 0.78,
      potential_duplicate_of: "ev_hale_payroll_old",
      superseded_by_id: null,
      supersedes_id: "ev_hale_payroll_old",
      human_review_status: "unreviewed",
      source_system: "data_room",
      external_item_id: null,
      external_thread_id: null,
      external_meeting_id: null,
      author: null,
      sender: null,
      participants: [],
      occurred_at: "2025-07-05T12:00:00.000Z",
      ingested_at: "2026-08-08T13:30:00.000Z",
      last_synchronized_at: null,
      subject: null,
      body: null,
      snippet: "Partner draws $980,000 — owner line not separated",
      page_count: 1,
      mime_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      size_bytes: 210_000,
    }),
    ev({
      id: "ev_hale_payroll_old",
      deal_id: DEAL,
      kind: "document",
      document_id: "doc_hale_payroll",
      filename: "Hale_Mercer_Payroll_Register_TTM.xlsx",
      title: "Payroll register (earlier export)",
      detected_type: "payroll_register",
      detected_period: "TTM 2025",
      detected_entity: ENTITY,
      file_format: "xlsx",
      processing_status: "needs_review",
      confidence: 0.78,
      potential_duplicate_of: "ev_hale_payroll_v2",
      superseded_by_id: "ev_hale_payroll_v2",
      supersedes_id: null,
      human_review_status: "unreviewed",
      source_system: "data_room",
      external_item_id: null,
      external_thread_id: null,
      external_meeting_id: null,
      author: null,
      sender: null,
      participants: [],
      occurred_at: "2025-07-01T12:00:00.000Z",
      ingested_at: "2026-08-08T13:22:00.000Z",
      last_synchronized_at: null,
      subject: null,
      body: null,
      snippet: "Partner compensation shown $980,000",
      page_count: 1,
      mime_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      size_bytes: 200_000,
    }),
    ev({
      id: "ev_hale_prod_old",
      deal_id: DEAL,
      kind: "document",
      document_id: "doc_hale_prod_old",
      filename: "Attorney Production.xlsx",
      title: "Attorney Production",
      detected_type: "production_report",
      detected_period: "TTM 2025",
      detected_entity: ENTITY,
      file_format: "xlsx",
      processing_status: "analyzed",
      confidence: 0.8,
      potential_duplicate_of: "ev_hale_prod_new",
      superseded_by_id: "ev_hale_prod_new",
      supersedes_id: null,
      human_review_status: "unreviewed",
      source_system: "data_room",
      external_item_id: null,
      external_thread_id: null,
      external_meeting_id: null,
      author: null,
      sender: null,
      participants: [],
      occurred_at: "2025-07-12T12:00:00.000Z",
      ingested_at: "2026-08-20T11:00:00.000Z",
      last_synchronized_at: null,
      subject: null,
      body: null,
      snippet: "Collections $7,980,000 — superseded by NEW",
      page_count: 3,
      mime_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      size_bytes: 160_000,
    }),
    ev({
      id: "ev_hale_prod_new",
      deal_id: DEAL,
      kind: "document",
      document_id: "doc_hale_prod_new",
      filename: "Attorney Production NEW.xlsx",
      title: "Attorney Production NEW",
      detected_type: "production_report",
      detected_period: "TTM 2025",
      detected_entity: ENTITY,
      file_format: "xlsx",
      processing_status: "analyzed",
      confidence: 0.91,
      potential_duplicate_of: "ev_hale_prod_old",
      superseded_by_id: null,
      supersedes_id: "ev_hale_prod_old",
      human_review_status: "unreviewed",
      source_system: "data_room",
      external_item_id: null,
      external_thread_id: null,
      external_meeting_id: null,
      author: null,
      sender: null,
      participants: [],
      occurred_at: "2025-07-20T12:00:00.000Z",
      ingested_at: "2026-08-22T15:20:00.000Z",
      last_synchronized_at: null,
      subject: null,
      body: null,
      snippet: "Collections $8,150,000 vs recorded revenue $8,400,000",
      page_count: 4,
      mime_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      size_bytes: 175_000,
    }),
    ev({
      id: "ev_hale_client_rev",
      deal_id: DEAL,
      kind: "document",
      document_id: "doc_hale_client_rev",
      filename: "Client Matter Revenue.xlsx",
      title: "Client Matter Revenue",
      detected_type: "customer_client_detail",
      detected_period: "TTM 2025",
      detected_entity: ENTITY,
      file_format: "xlsx",
      processing_status: "analyzed",
      confidence: 0.88,
      potential_duplicate_of: null,
      superseded_by_id: null,
      supersedes_id: null,
      human_review_status: "unreviewed",
      source_system: "data_room",
      external_item_id: null,
      external_thread_id: null,
      external_meeting_id: null,
      author: null,
      sender: null,
      participants: [],
      occurred_at: "2025-07-15T12:00:00.000Z",
      ingested_at: "2026-08-16T14:05:00.000Z",
      last_synchronized_at: null,
      subject: null,
      body: null,
      snippet: "Billed $8,280,000 · collected $8,400,000",
      page_count: 1,
      mime_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      size_bytes: 190_000,
    }),
    ev({
      id: "ev_hale_ar",
      deal_id: DEAL,
      kind: "document",
      document_id: "doc_hale_ar_aging",
      filename: "AR Aging.xlsx",
      title: "AR Aging",
      detected_type: "ar",
      detected_period: "TTM 2025",
      detected_entity: ENTITY,
      file_format: "xlsx",
      processing_status: "analyzed",
      confidence: 0.9,
      potential_duplicate_of: null,
      superseded_by_id: null,
      supersedes_id: null,
      human_review_status: "unreviewed",
      source_system: "data_room",
      external_item_id: null,
      external_thread_id: null,
      external_meeting_id: null,
      author: null,
      sender: null,
      participants: [],
      occurred_at: "2025-07-01T12:00:00.000Z",
      ingested_at: "2026-08-17T09:40:00.000Z",
      last_synchronized_at: null,
      subject: null,
      body: null,
      snippet: "AR $1,120,000",
      page_count: 1,
      mime_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      size_bytes: 95_000,
    }),
    ev({
      id: "ev_hale_lease",
      deal_id: DEAL,
      kind: "document",
      document_id: "doc_hale_lease_messy",
      filename: "Lease.pdf",
      title: "Office lease — 333 W Wacker",
      detected_type: "lease",
      detected_period: null,
      detected_entity: ENTITY,
      file_format: "pdf",
      processing_status: "analyzed",
      confidence: 0.93,
      potential_duplicate_of: "ev_hale_lease_old",
      superseded_by_id: null,
      supersedes_id: null,
      human_review_status: "confirmed",
      source_system: "data_room",
      external_item_id: null,
      external_thread_id: null,
      external_meeting_id: null,
      author: null,
      sender: null,
      participants: [],
      occurred_at: "2023-05-01T12:00:00.000Z",
      ingested_at: "2026-07-29T10:05:00.000Z",
      last_synchronized_at: null,
      subject: null,
      body: null,
      snippet: "333 W Wacker · expires 30 Apr 2028 · rent $540,000",
      page_count: 42,
      mime_type: "application/pdf",
      size_bytes: 2_800_000,
    }),
    ev({
      id: "ev_hale_lease_old",
      deal_id: DEAL,
      kind: "document",
      document_id: "doc_hale_lease",
      filename: "333_W_Wacker_Office_Lease.pdf",
      title: "333 W Wacker Office Lease (banker name)",
      detected_type: "lease",
      detected_period: null,
      detected_entity: ENTITY,
      file_format: "pdf",
      processing_status: "analyzed",
      confidence: 0.92,
      potential_duplicate_of: "ev_hale_lease",
      superseded_by_id: null,
      supersedes_id: null,
      human_review_status: "confirmed",
      source_system: "data_room",
      external_item_id: null,
      external_thread_id: null,
      external_meeting_id: null,
      author: null,
      sender: null,
      participants: [],
      occurred_at: "2023-05-01T12:00:00.000Z",
      ingested_at: "2026-07-29T10:00:00.000Z",
      last_synchronized_at: null,
      subject: null,
      body: null,
      snippet: "Same lease; banker filename",
      page_count: 42,
      mime_type: "application/pdf",
      size_bytes: 2_800_000,
    }),
    ev({
      id: "ev_hale_org",
      deal_id: DEAL,
      kind: "document",
      document_id: "doc_hale_org_messy",
      filename: "Org Chart.pdf",
      title: "Org Chart",
      detected_type: "other",
      detected_period: null,
      detected_entity: ENTITY,
      file_format: "pdf",
      processing_status: "analyzed",
      confidence: 0.9,
      potential_duplicate_of: null,
      superseded_by_id: null,
      supersedes_id: null,
      human_review_status: "confirmed",
      source_system: "data_room",
      external_item_id: null,
      external_thread_id: null,
      external_meeting_id: null,
      author: null,
      sender: null,
      participants: [],
      occurred_at: "2026-07-01T12:00:00.000Z",
      ingested_at: "2026-07-21T12:50:00.000Z",
      last_synchronized_at: null,
      subject: null,
      body: null,
      snippet: "18 attorneys · 4 partners",
      page_count: 2,
      mime_type: "application/pdf",
      size_bytes: 180_000,
    }),
    ev({
      id: "ev_hale_nda",
      deal_id: DEAL,
      kind: "document",
      document_id: "doc_hale_nda_messy",
      filename: "NDA executed.pdf",
      title: "NDA executed",
      detected_type: "legal",
      detected_period: null,
      detected_entity: ENTITY,
      file_format: "pdf",
      processing_status: "analyzed",
      confidence: 0.94,
      potential_duplicate_of: null,
      superseded_by_id: null,
      supersedes_id: null,
      human_review_status: "confirmed",
      source_system: "data_room",
      external_item_id: null,
      external_thread_id: null,
      external_meeting_id: null,
      author: null,
      sender: null,
      participants: [],
      occurred_at: "2026-06-18T12:00:00.000Z",
      ingested_at: "2026-06-20T09:40:00.000Z",
      last_synchronized_at: null,
      subject: null,
      body: null,
      snippet: "Executed NDA",
      page_count: 7,
      mime_type: "application/pdf",
      size_bytes: 220_000,
    }),
    ev({
      id: "ev_hale_loi",
      deal_id: DEAL,
      kind: "document",
      document_id: "doc_hale_loi",
      filename: "Indication_or_LOI.pdf",
      title: "Seller indication / draft LOI terms",
      detected_type: "purchase_agreement_loi",
      detected_period: null,
      detected_entity: ENTITY,
      file_format: "pdf",
      processing_status: "analyzed",
      confidence: 0.89,
      potential_duplicate_of: null,
      superseded_by_id: null,
      supersedes_id: null,
      human_review_status: "unreviewed",
      source_system: "data_room",
      external_item_id: null,
      external_thread_id: null,
      external_meeting_id: null,
      author: "Harris Williams",
      sender: null,
      participants: [],
      occurred_at: "2026-08-02T12:00:00.000Z",
      ingested_at: "2026-08-03T16:00:00.000Z",
      last_synchronized_at: null,
      subject: null,
      body: null,
      snippet: "Seller ask $16,800,000 · 6.2x pro forma",
      page_count: 6,
      mime_type: "application/pdf",
      size_bytes: 340_000,
    }),
    ev({
      id: "ev_hale_email_ps",
      deal_id: DEAL,
      kind: "email",
      document_id: "doc_hale_email_ps",
      filename: "RE professional services expenses.eml",
      title: "RE: professional services expenses",
      detected_type: "email",
      detected_period: "TTM 2025",
      detected_entity: ENTITY,
      file_format: "eml",
      processing_status: "analyzed",
      confidence: 0.87,
      potential_duplicate_of: null,
      superseded_by_id: null,
      supersedes_id: null,
      human_review_status: "unreviewed",
      source_system: "gmail",
      external_item_id: "gmail_msg_ps_18421",
      external_thread_id: "gmail_thread_ps_992",
      external_meeting_id: null,
      author: "Claire Hoffman",
      sender: "choffman@halemercer.com",
      participants: ["Claire Hoffman", "Elena Vargas", "Marcus Webb"],
      occurred_at: "2026-08-25T14:48:00.000Z",
      ingested_at: "2026-08-25T15:10:00.000Z",
      last_synchronized_at: "2026-08-25T15:10:00.000Z",
      subject: "RE: professional services expenses",
      body: "Elena — on the $180k you flagged after the Schiff Hardin matter: $40k is Relativity / e-discovery on the Patel construction case (one-time, closed June). The remaining ~$140k is a mix of outside coverage counsel and a fractional CFO we still use. I do not have vendor invoices for the CFO line in this folder. — Claire",
      snippet: "$40k e-discovery is one-time; ~$140k still unexplained",
      page_count: 1,
      mime_type: "message/rfc822",
      size_bytes: 18_000,
    }),
    ev({
      id: "ev_hale_email_lease",
      deal_id: DEAL,
      kind: "email",
      document_id: "doc_hale_email_lease",
      filename: "Re office lease 333 W Wacker.eml",
      title: "Re: office lease 333 W Wacker",
      detected_type: "email",
      detected_period: null,
      detected_entity: ENTITY,
      file_format: "eml",
      processing_status: "analyzed",
      confidence: 0.86,
      potential_duplicate_of: null,
      superseded_by_id: null,
      supersedes_id: null,
      human_review_status: "unreviewed",
      source_system: "gmail",
      external_item_id: "gmail_msg_lease_21004",
      external_thread_id: "gmail_thread_lease_441",
      external_meeting_id: null,
      author: "Jonathan Hale",
      sender: "jhale@halemercer.com",
      participants: ["Jonathan Hale", "Priya Shah"],
      occurred_at: "2026-08-24T18:55:00.000Z",
      ingested_at: "2026-08-24T19:20:00.000Z",
      last_synchronized_at: "2026-08-24T19:20:00.000Z",
      subject: "Re: office lease — 333 W Wacker",
      body: "Priya — expiry is 30 April 2028. There is a 5-year renewal option at then-market, not a fixed-rate option. We have not opened that conversation with the landlord. We would stay in the space post-close; this is not a relocate-and-save story on day one. — Jonathan",
      snippet: "Expires Apr 2028 · renewal at then-market · staying in place",
      page_count: 1,
      mime_type: "message/rfc822",
      size_bytes: 14_000,
    }),
    ev({
      id: "ev_hale_note_retention",
      deal_id: DEAL,
      kind: "meeting_note",
      document_id: "doc_hale_note_retention",
      filename: "Partner retention discussion.md",
      title: "Partner retention — management meeting",
      detected_type: "meeting_note_transcript",
      detected_period: null,
      detected_entity: ENTITY,
      file_format: "md",
      processing_status: "analyzed",
      confidence: 0.83,
      potential_duplicate_of: null,
      superseded_by_id: null,
      supersedes_id: null,
      human_review_status: "unreviewed",
      source_system: "granola",
      external_item_id: "granola_note_ret_77",
      external_thread_id: null,
      external_meeting_id: "granola_mtg_ret_77",
      author: "Elena Vargas",
      sender: null,
      participants: ["Elena Vargas", "Jonathan Hale", "Daniel Mercer"],
      occurred_at: "2026-08-25T20:00:00.000Z",
      ingested_at: "2026-08-25T21:00:00.000Z",
      last_synchronized_at: "2026-08-25T21:00:00.000Z",
      subject: "Partner retention discussion",
      body: "Mercer said he is 'open to staying' but wants a two-year retention package tied to his book, not a standard employment agreement. Hale pushed that origination credit must survive a sale. No signed term sheet. Concentration: Mercer ~17% of revenue; top three ~31%. Elena flagged that an indication before retention terms is not defensible.",
      snippet: "Mercer open to staying — no signed retention · 17% of revenue",
      page_count: 1,
      mime_type: "text/markdown",
      size_bytes: 6_400,
    }),
    ev({
      id: "ev_hale_note_occupancy",
      deal_id: DEAL,
      kind: "meeting_note",
      document_id: "doc_hale_note_occupancy",
      filename: "Occupancy and expenses post-close.md",
      title: "Occupancy / expenses remaining post-close",
      detected_type: "meeting_note_transcript",
      detected_period: "TTM 2025",
      detected_entity: ENTITY,
      file_format: "md",
      processing_status: "analyzed",
      confidence: 0.85,
      potential_duplicate_of: null,
      superseded_by_id: null,
      supersedes_id: null,
      human_review_status: "unreviewed",
      source_system: "granola",
      external_item_id: "granola_note_occ_81",
      external_thread_id: null,
      external_meeting_id: "granola_mtg_occ_81",
      author: "Marcus Webb",
      sender: null,
      participants: ["Marcus Webb", "Claire Hoffman", "Jonathan Hale"],
      occurred_at: "2026-08-26T17:30:00.000Z",
      ingested_at: "2026-08-26T18:15:00.000Z",
      last_synchronized_at: "2026-08-26T18:15:00.000Z",
      subject: "Occupancy and expenses remaining post-close",
      body: "Claire: 'We are not leaving 333 W Wacker. The occupancy number does not go away at close. If anything we are under-rented versus a new build-out.' Jonathan agreed the $120k 'excess occupancy' add-back is a buyer construct — the firm will keep paying the lease. Market-rent savings are not achievable in year one. Marcus noted this challenges the proposed occupancy add-back.",
      snippet: "Expenses remain after close — occupancy add-back not achievable Y1",
      page_count: 1,
      mime_type: "text/markdown",
      size_bytes: 7_200,
    }),
  ];
}

function versions(): DocumentVersion[] {
  return [
    {
      id: "ver_hale_pl24_final",
      organization_id: ORG,
      deal_id: DEAL,
      evidence_item_id: "ev_hale_pl_2024_final",
      version_label: "FINAL",
      supersedes_id: null,
      is_current: false,
    },
    {
      id: "ver_hale_pl24_updated",
      organization_id: ORG,
      deal_id: DEAL,
      evidence_item_id: "ev_hale_pl_2024_updated",
      version_label: "FINAL UPDATED",
      supersedes_id: "ver_hale_pl24_final",
      is_current: true,
    },
    {
      id: "ver_hale_prod_old",
      organization_id: ORG,
      deal_id: DEAL,
      evidence_item_id: "ev_hale_prod_old",
      version_label: "v1",
      supersedes_id: null,
      is_current: false,
    },
    {
      id: "ver_hale_prod_new",
      organization_id: ORG,
      deal_id: DEAL,
      evidence_item_id: "ev_hale_prod_new",
      version_label: "NEW",
      supersedes_id: "ver_hale_prod_old",
      is_current: true,
    },
  ];
}

function extractions(): Extraction[] {
  return items().map((item) => ({
    id: `ex_${item.id}`,
    organization_id: ORG,
    deal_id: DEAL,
    evidence_item_id: item.id,
    method: "seeded_metadata",
    status: "analyzed",
    started_at: item.ingested_at,
    completed_at: item.ingested_at,
    notes: "Deterministic extract from filename + seeded metadata. No live LLM.",
  }));
}

function facts(): ExtractedFact[] {
  const base = {
    assigned_user_id: null as string | null,
    unit: "usd" as const,
    extraction_method: "seeded_metadata" as const,
  };
  return [
    fact({
      ...base,
      id: "fact_hale_fy23_rev",
      deal_id: DEAL,
      evidence_item_id: "ev_hale_pl_2023",
      extraction_id: "ex_ev_hale_pl_2023",
      fact_kind: "statement_line",
      label: "FY2023 revenue",
      period_label: "FY2023",
      entity: ENTITY,
      numeric_value: 7_370_000,
      text_value: null,
      page: 1,
      sheet: "P&L",
      cell: "B12",
      section: "Revenue",
      extracted_value: "7370000",
      confidence: 0.97,
      review_status: "accepted",
      conflicting_fact_ids: [],
      claim_kind: "source_fact",
      linked_metric_key: "revenue",
      linked_period_id: "hale_fy2023",
    }),
    fact({
      ...base,
      id: "fact_hale_fy23_ebitda",
      deal_id: DEAL,
      evidence_item_id: "ev_hale_pl_2023",
      extraction_id: "ex_ev_hale_pl_2023",
      fact_kind: "statement_line",
      label: "FY2023 reported EBITDA",
      period_label: "FY2023",
      entity: ENTITY,
      numeric_value: 1_700_000,
      text_value: null,
      page: 1,
      sheet: "P&L",
      cell: "B28",
      section: "EBITDA",
      extracted_value: "1700000",
      confidence: 0.97,
      review_status: "accepted",
      conflicting_fact_ids: [],
      claim_kind: "source_fact",
      linked_metric_key: "reported_ebitda",
      linked_period_id: "hale_fy2023",
    }),
    fact({
      ...base,
      id: "fact_hale_fy24_final_rev",
      deal_id: DEAL,
      evidence_item_id: "ev_hale_pl_2024_final",
      extraction_id: "ex_ev_hale_pl_2024_final",
      fact_kind: "statement_line",
      label: "FY2024 revenue (FINAL)",
      period_label: "FY2024",
      entity: ENTITY,
      numeric_value: 7_695_000,
      text_value: null,
      page: 1,
      sheet: "P&L",
      cell: "B12",
      section: "Revenue",
      extracted_value: "7695000",
      confidence: 0.9,
      review_status: "rejected",
      conflicting_fact_ids: ["fact_hale_fy24_upd_rev"],
      claim_kind: "source_fact",
      linked_metric_key: "revenue",
      linked_period_id: "hale_fy2024",
    }),
    fact({
      ...base,
      id: "fact_hale_fy24_final_ebitda",
      deal_id: DEAL,
      evidence_item_id: "ev_hale_pl_2024_final",
      extraction_id: "ex_ev_hale_pl_2024_final",
      fact_kind: "statement_line",
      label: "FY2024 EBITDA (FINAL)",
      period_label: "FY2024",
      entity: ENTITY,
      numeric_value: 1_875_000,
      text_value: null,
      page: 1,
      sheet: "P&L",
      cell: "B28",
      section: "EBITDA",
      extracted_value: "1875000",
      confidence: 0.9,
      review_status: "rejected",
      conflicting_fact_ids: ["fact_hale_fy24_upd_ebitda"],
      claim_kind: "source_fact",
      linked_metric_key: "reported_ebitda",
      linked_period_id: "hale_fy2024",
    }),
    fact({
      ...base,
      id: "fact_hale_fy24_upd_rev",
      deal_id: DEAL,
      evidence_item_id: "ev_hale_pl_2024_updated",
      extraction_id: "ex_ev_hale_pl_2024_updated",
      fact_kind: "statement_line",
      label: "FY2024 revenue (UPDATED)",
      period_label: "FY2024",
      entity: ENTITY,
      numeric_value: 7_720_000,
      text_value: null,
      page: 1,
      sheet: "P&L",
      cell: "B12",
      section: "Revenue",
      extracted_value: "7720000",
      confidence: 0.97,
      review_status: "accepted",
      conflicting_fact_ids: ["fact_hale_fy24_final_rev", "fact_hale_tax24_rev"],
      claim_kind: "source_fact",
      linked_metric_key: "revenue",
      linked_period_id: "hale_fy2024",
    }),
    fact({
      ...base,
      id: "fact_hale_fy24_upd_ebitda",
      deal_id: DEAL,
      evidence_item_id: "ev_hale_pl_2024_updated",
      extraction_id: "ex_ev_hale_pl_2024_updated",
      fact_kind: "statement_line",
      label: "FY2024 reported EBITDA (UPDATED)",
      period_label: "FY2024",
      entity: ENTITY,
      numeric_value: 1_900_000,
      text_value: null,
      page: 1,
      sheet: "P&L",
      cell: "B28",
      section: "EBITDA",
      extracted_value: "1900000",
      confidence: 0.97,
      review_status: "accepted",
      conflicting_fact_ids: ["fact_hale_fy24_final_ebitda"],
      claim_kind: "source_fact",
      linked_metric_key: "reported_ebitda",
      linked_period_id: "hale_fy2024",
    }),
    fact({
      ...base,
      id: "fact_hale_tax24_rev",
      deal_id: DEAL,
      evidence_item_id: "ev_hale_tax_2024",
      extraction_id: "ex_ev_hale_tax_2024",
      fact_kind: "statement_line",
      label: "FY2024 tax-return cash receipts",
      period_label: "FY2024",
      entity: ENTITY,
      numeric_value: 7_480_000,
      text_value: null,
      page: 4,
      sheet: null,
      cell: null,
      section: "Form 1065 Line 1a",
      extracted_value: "7480000",
      confidence: 0.94,
      review_status: "pending",
      conflicting_fact_ids: ["fact_hale_fy24_upd_rev"],
      claim_kind: "source_fact",
      linked_metric_key: "revenue",
      linked_period_id: "hale_fy2024",
    }),
    fact({
      ...base,
      id: "fact_hale_ttm_rev",
      deal_id: DEAL,
      evidence_item_id: "ev_hale_ttm_pl",
      extraction_id: "ex_ev_hale_ttm_pl",
      fact_kind: "statement_line",
      label: "TTM 2025 revenue",
      period_label: "TTM 2025",
      entity: ENTITY,
      numeric_value: 8_400_000,
      text_value: null,
      page: 1,
      sheet: null,
      cell: null,
      section: "Revenue",
      extracted_value: "8400000",
      confidence: 0.98,
      review_status: "accepted",
      conflicting_fact_ids: ["fact_hale_prod_new", "fact_hale_qb_h1"],
      claim_kind: "source_fact",
      linked_metric_key: "revenue",
      linked_period_id: "hale_ttm2025",
    }),
    fact({
      ...base,
      id: "fact_hale_ttm_ebitda",
      deal_id: DEAL,
      evidence_item_id: "ev_hale_ttm_pl",
      extraction_id: "ex_ev_hale_ttm_pl",
      fact_kind: "statement_line",
      label: "TTM 2025 reported EBITDA",
      period_label: "TTM 2025",
      entity: ENTITY,
      numeric_value: 2_100_000,
      text_value: null,
      page: 2,
      sheet: null,
      cell: null,
      section: "EBITDA",
      extracted_value: "2100000",
      confidence: 0.98,
      review_status: "accepted",
      conflicting_fact_ids: [],
      claim_kind: "source_fact",
      linked_metric_key: "reported_ebitda",
      linked_period_id: "hale_ttm2025",
    }),
    fact({
      ...base,
      id: "fact_hale_ttm_owner",
      deal_id: DEAL,
      evidence_item_id: "ev_hale_ttm_pl",
      extraction_id: "ex_ev_hale_ttm_pl",
      fact_kind: "owner_comp",
      label: "TTM owner compensation (P&L)",
      period_label: "TTM 2025",
      entity: ENTITY,
      numeric_value: 1_420_000,
      text_value: null,
      page: 3,
      sheet: null,
      cell: null,
      section: "Owner compensation",
      extracted_value: "1420000",
      confidence: 0.96,
      review_status: "accepted",
      conflicting_fact_ids: ["fact_hale_payroll_partners"],
      claim_kind: "source_fact",
      linked_metric_key: "opex_owner",
      linked_period_id: "hale_ttm2025",
    }),
    fact({
      ...base,
      id: "fact_hale_ttm_ps",
      deal_id: DEAL,
      evidence_item_id: "ev_hale_ttm_pl",
      extraction_id: "ex_ev_hale_ttm_pl",
      fact_kind: "expense_detail",
      label: "TTM professional services",
      period_label: "TTM 2025",
      entity: ENTITY,
      numeric_value: 248_000,
      text_value: null,
      page: 3,
      sheet: null,
      cell: null,
      section: "Professional services",
      extracted_value: "248000",
      confidence: 0.95,
      review_status: "accepted",
      conflicting_fact_ids: [],
      claim_kind: "source_fact",
      linked_metric_key: "opex_professional_services",
      linked_period_id: "hale_ttm2025",
    }),
    fact({
      ...base,
      id: "fact_hale_qb_h1",
      deal_id: DEAL,
      evidence_item_id: "ev_hale_qb",
      extraction_id: "ex_ev_hale_qb",
      fact_kind: "revenue_detail",
      label: "H1 2025 QuickBooks revenue (sum of months)",
      period_label: "H1 2025",
      entity: ENTITY,
      numeric_value: 4_050_000,
      text_value: null,
      page: 1,
      sheet: "Monthly",
      cell: "H14",
      section: "Jan–June total",
      extracted_value: "4050000",
      confidence: 0.82,
      review_status: "pending",
      conflicting_fact_ids: ["fact_hale_ttm_rev"],
      claim_kind: "source_fact",
      linked_metric_key: "revenue",
      linked_period_id: null,
    }),
    fact({
      ...base,
      id: "fact_hale_payroll_partners",
      deal_id: DEAL,
      evidence_item_id: "ev_hale_payroll_v2",
      extraction_id: "ex_ev_hale_payroll_v2",
      fact_kind: "payroll",
      label: "Partner draws in payroll register",
      period_label: "TTM 2025",
      entity: ENTITY,
      numeric_value: 980_000,
      text_value: "Owner compensation not separately coded",
      page: 1,
      sheet: "Register",
      cell: "D40",
      section: "Partner draws",
      extracted_value: "980000",
      confidence: 0.8,
      review_status: "pending",
      conflicting_fact_ids: ["fact_hale_ttm_owner"],
      claim_kind: "source_fact",
      linked_metric_key: "opex_owner",
      linked_period_id: "hale_ttm2025",
    }),
    fact({
      ...base,
      id: "fact_hale_prod_new",
      deal_id: DEAL,
      evidence_item_id: "ev_hale_prod_new",
      extraction_id: "ex_ev_hale_prod_new",
      fact_kind: "vertical_metric",
      label: "Attorney production collections (NEW)",
      period_label: "TTM 2025",
      entity: ENTITY,
      numeric_value: 8_150_000,
      text_value: null,
      page: 1,
      sheet: "Summary",
      cell: "E22",
      section: "Collections",
      extracted_value: "8150000",
      confidence: 0.9,
      review_status: "pending",
      conflicting_fact_ids: ["fact_hale_ttm_rev", "fact_hale_prod_old"],
      claim_kind: "source_fact",
      linked_metric_key: "revenue",
      linked_period_id: "hale_ttm2025",
    }),
    fact({
      ...base,
      id: "fact_hale_prod_old",
      deal_id: DEAL,
      evidence_item_id: "ev_hale_prod_old",
      extraction_id: "ex_ev_hale_prod_old",
      fact_kind: "vertical_metric",
      label: "Attorney production collections (v1)",
      period_label: "TTM 2025",
      entity: ENTITY,
      numeric_value: 7_980_000,
      text_value: null,
      page: 1,
      sheet: "Summary",
      cell: "E22",
      section: "Collections",
      extracted_value: "7980000",
      confidence: 0.78,
      review_status: "rejected",
      conflicting_fact_ids: ["fact_hale_prod_new"],
      claim_kind: "source_fact",
      linked_metric_key: "revenue",
      linked_period_id: "hale_ttm2025",
    }),
    fact({
      ...base,
      id: "fact_hale_lease_expiry",
      deal_id: DEAL,
      evidence_item_id: "ev_hale_lease",
      extraction_id: "ex_ev_hale_lease",
      fact_kind: "contractual_date",
      label: "Lease expiry",
      period_label: null,
      entity: ENTITY,
      numeric_value: null,
      text_value: "2028-04-30",
      unit: null,
      page: 3,
      sheet: null,
      cell: null,
      section: "Term",
      extracted_value: "2028-04-30",
      confidence: 0.96,
      review_status: "accepted",
      conflicting_fact_ids: [],
      claim_kind: "source_fact",
      linked_metric_key: null,
      linked_period_id: null,
    }),
    fact({
      ...base,
      id: "fact_hale_lease_rent",
      deal_id: DEAL,
      evidence_item_id: "ev_hale_lease",
      extraction_id: "ex_ev_hale_lease",
      fact_kind: "lease_commitment",
      label: "Annual rent — 333 W Wacker",
      period_label: "TTM 2025",
      entity: ENTITY,
      numeric_value: 540_000,
      text_value: "333 W Wacker, Chicago",
      page: 8,
      sheet: null,
      cell: null,
      section: "Article 3 — Rent",
      extracted_value: "540000",
      confidence: 0.94,
      review_status: "accepted",
      conflicting_fact_ids: [],
      claim_kind: "source_fact",
      linked_metric_key: "opex_occupancy",
      linked_period_id: "hale_ttm2025",
    }),
    fact({
      ...base,
      id: "fact_hale_email_ps_40k",
      deal_id: DEAL,
      evidence_item_id: "ev_hale_email_ps",
      extraction_id: "ex_ev_hale_email_ps",
      fact_kind: "expense_detail",
      label: "E-discovery / Relativity (seller explanation)",
      period_label: "TTM 2025",
      entity: ENTITY,
      numeric_value: 40_000,
      text_value: "Partial explanation of $180k unexplained professional services",
      page: 1,
      sheet: null,
      cell: null,
      section: "Email body",
      extracted_value: "40000",
      confidence: 0.84,
      review_status: "pending",
      conflicting_fact_ids: [],
      claim_kind: "ai_inference",
      linked_metric_key: "opex_professional_services",
      linked_period_id: "hale_ttm2025",
    }),
    fact({
      ...base,
      id: "fact_hale_conc_mercer",
      deal_id: DEAL,
      evidence_item_id: "ev_hale_prod_new",
      extraction_id: "ex_ev_hale_prod_new",
      fact_kind: "concentration",
      label: "Daniel Mercer collections share",
      period_label: "TTM 2025",
      entity: "Daniel Mercer",
      numeric_value: 0.17,
      text_value: "Daniel Mercer",
      unit: "share",
      page: 1,
      sheet: "By attorney",
      cell: "C4",
      section: "Top attorney",
      extracted_value: "0.17",
      confidence: 0.91,
      review_status: "accepted",
      conflicting_fact_ids: [],
      claim_kind: "source_fact",
      linked_metric_key: null,
      linked_period_id: "hale_ttm2025",
    }),
  ];
}

function conflicts(): Conflict[] {
  return [
    {
      id: "cf_hale_pl24_versions",
      organization_id: ORG,
      deal_id: DEAL,
      description: "P&L 2024 FINAL UPDATED supersedes P&L 2024 FINAL (small revenue/EBITDA delta).",
      source_a_id: "ev_hale_pl_2024_final",
      source_b_id: "ev_hale_pl_2024_updated",
      source_a_label: "P&L 2024 FINAL.xlsx · $7,695,000 rev / $1,875,000 EBITDA",
      source_b_label: "P&L 2024 FINAL UPDATED.xlsx · $7,720,000 rev / $1,900,000 EBITDA",
      value_a: 7_695_000,
      value_b: 7_720_000,
      difference: 25_000,
      materiality: "notable",
      ai_interpretation:
        "UPDATED is the later file and matches the reconstructed FY2024 history. FINAL should be treated as superseded, not as a second year.",
      recommended_action: "Accept UPDATED as the FY2024 source; mark FINAL superseded.",
      owner_user_id: MARCUS,
      status: "accepted_difference",
      resolution_notes: "Reviewed position uses UPDATED. FINAL retained for audit trail.",
      linked_request_id: "dil_hale_pls",
      linked_adjustment_id: null,
      linked_task_id: null,
      related_fact_ids: ["fact_hale_fy24_final_rev", "fact_hale_fy24_upd_rev"],
    },
    {
      id: "cf_hale_tax_vs_pl",
      organization_id: ORG,
      deal_id: DEAL,
      description: "2024 tax-return cash receipts differ from annual P&L revenue by a material, explainable amount.",
      source_a_id: "ev_hale_tax_2024",
      source_b_id: "ev_hale_pl_2024_updated",
      source_a_label: "Tax Return 2024.pdf · cash $7,480,000",
      source_b_label: "P&L 2024 FINAL UPDATED.xlsx · accrual $7,720,000",
      value_a: 7_480_000,
      value_b: 7_720_000,
      difference: 240_000,
      materiality: "material",
      ai_interpretation:
        "$240k / 3.1% is consistent with cash-vs-accrual plus owner personal items run through the partnership return. Both numbers should stay visible until we have a book-to-tax bridge.",
      recommended_action: "Request the book-to-tax reconciliation; do not overwrite accepted P&L revenue.",
      owner_user_id: MARCUS,
      status: "follow_up_required",
      resolution_notes: "",
      linked_request_id: "dil_hale_tax_2024",
      linked_adjustment_id: null,
      linked_task_id: null,
      related_fact_ids: ["fact_hale_tax24_rev", "fact_hale_fy24_upd_rev"],
    },
    {
      id: "cf_hale_payroll_vs_owner",
      organization_id: ORG,
      deal_id: DEAL,
      description: "Payroll Detail v2 partner draws do not reconcile to P&L owner compensation.",
      source_a_id: "ev_hale_payroll_v2",
      source_b_id: "ev_hale_ttm_pl",
      source_a_label: "Payroll Detail v2.xlsx · partner draws $980,000",
      source_b_label: "Hale_Mercer_TTM_2025_PL.pdf · owner compensation $1,420,000",
      value_a: 980_000,
      value_b: 1_420_000,
      difference: 440_000,
      materiality: "material",
      ai_interpretation:
        "Owner compensation is not clearly separated in payroll. The $310k accepted add-back assumes P&L $1,420,000 vs a $1,110,000 replacement stack — that math is only as good as the P&L line.",
      recommended_action: "Convert to a seller request for partner-level compensation detail.",
      owner_user_id: MARCUS,
      status: "investigating",
      resolution_notes: "",
      linked_request_id: "dil_hale_payroll",
      linked_adjustment_id: "adj_hale_owner",
      linked_task_id: null,
      related_fact_ids: ["fact_hale_payroll_partners", "fact_hale_ttm_owner"],
    },
    {
      id: "cf_hale_qb_vs_ttm",
      organization_id: ORG,
      deal_id: DEAL,
      description: "Monthly QuickBooks Jan–June do not sum to half of TTM (or half of FY2024).",
      source_a_id: "ev_hale_qb",
      source_b_id: "ev_hale_ttm_pl",
      source_a_label: "QB export jan-june.xlsx · $4,050,000",
      source_b_label: "Half of TTM 2025 revenue = $4,200,000",
      value_a: 4_050_000,
      value_b: 4_200_000,
      difference: 150_000,
      materiality: "notable",
      ai_interpretation:
        "Timing and classification. Half of TTM is $4.20M; half of FY2024 is $3.86M. H1 2025 sitting at $4.05M is plausible seasonality plus a mapping difference — not a restatement by itself.",
      recommended_action: "Ask for a monthly roll-forward that ties to the TTM P&L.",
      owner_user_id: MARCUS,
      status: "unreviewed",
      resolution_notes: "",
      linked_request_id: "dil_hale_monthly",
      linked_adjustment_id: null,
      linked_task_id: null,
      related_fact_ids: ["fact_hale_qb_h1", "fact_hale_ttm_rev"],
    },
    {
      id: "cf_hale_prod_vs_rev",
      organization_id: ORG,
      deal_id: DEAL,
      description: "Attorney Production NEW totals differ from recorded TTM revenue (write-offs / unbilled / origination credit).",
      source_a_id: "ev_hale_prod_new",
      source_b_id: "ev_hale_ttm_pl",
      source_a_label: "Attorney Production NEW.xlsx · $8,150,000 collections",
      source_b_label: "TTM P&L revenue $8,400,000",
      value_a: 8_150_000,
      value_b: 8_400_000,
      difference: 250_000,
      materiality: "material",
      ai_interpretation:
        "NEW supersedes the $7.98M file. The remaining $250k vs recorded revenue is consistent with write-offs, unbilled WIP, and origination credit that never hits collections.",
      recommended_action: "Request a collections-to-revenue bridge before treating production as the revenue source.",
      owner_user_id: MARCUS,
      status: "unreviewed",
      resolution_notes: "",
      linked_request_id: "dil_hale_production",
      linked_adjustment_id: null,
      linked_task_id: null,
      related_fact_ids: ["fact_hale_prod_new", "fact_hale_ttm_rev"],
    },
    {
      id: "cf_hale_owner_not_separated",
      organization_id: ORG,
      deal_id: DEAL,
      description: "Owner compensation is not clearly separated in the payroll register.",
      source_a_id: "ev_hale_payroll_v2",
      source_b_id: "ev_hale_ttm_pl",
      source_a_label: "Payroll Detail v2.xlsx · no owner code",
      source_b_label: "TTM P&L owner compensation $1,420,000",
      value_a: null,
      value_b: 1_420_000,
      difference: null,
      materiality: "material",
      ai_interpretation:
        "Without a coded owner line, the accepted $310k normalization is an approved assumption sitting on a P&L total, not a payroll fact.",
      recommended_action: "Keep the add-back accepted only as an assumption until partner-level detail arrives.",
      owner_user_id: MARCUS,
      status: "investigating",
      resolution_notes: "",
      linked_request_id: "dil_hale_partner_comp",
      linked_adjustment_id: "adj_hale_owner",
      linked_task_id: null,
      related_fact_ids: ["fact_hale_payroll_partners", "fact_hale_ttm_owner"],
    },
    {
      id: "cf_hale_ps_unexplained",
      organization_id: ORG,
      deal_id: DEAL,
      description: "Professional services TTM $248k: $85k one-time accepted, $180k unexplained — seller email explains only $40k.",
      source_a_id: "ev_hale_email_ps",
      source_b_id: "ev_hale_ttm_pl",
      source_a_label: "Seller email · $40k Relativity / e-discovery",
      source_b_label: "TTM professional services $248,000 − $85,000 accepted = $180,000",
      value_a: 40_000,
      value_b: 180_000,
      difference: 140_000,
      materiality: "material",
      ai_interpretation:
        "The email is a partial answer. Suggest marking the professional-services request received/under review — not complete — until the remaining $140k is supported.",
      recommended_action: "Approve the suggested diligence-status update only after a human reviews the email.",
      owner_user_id: MARCUS,
      status: "follow_up_required",
      resolution_notes: "",
      linked_request_id: "dil_hale_ps",
      linked_adjustment_id: "adj_hale_legal",
      linked_task_id: null,
      related_fact_ids: ["fact_hale_ttm_ps", "fact_hale_email_ps_40k"],
    },
    {
      id: "cf_hale_occupancy_challenge",
      organization_id: ORG,
      deal_id: DEAL,
      description: "Meeting note challenges the occupancy add-back — expenses remain after close.",
      source_a_id: "ev_hale_note_occupancy",
      source_b_id: "ev_hale_lease",
      source_a_label: "Occupancy and expenses post-close.md",
      source_b_label: "Proposed $120k excess occupancy vs lease $540k",
      value_a: 0,
      value_b: 120_000,
      difference: 120_000,
      materiality: "material",
      ai_interpretation:
        "Management says they will stay in the space. The $120k add-back is a buyer construct, not a cost that disappears at close. Approving this interpretation should move occupancy to needs-review — not silently reject it.",
      recommended_action: "Flag the occupancy adjustment for reconsideration after human approval.",
      owner_user_id: MARCUS,
      status: "unreviewed",
      resolution_notes: "",
      linked_request_id: "dil_hale_lease",
      linked_adjustment_id: "adj_hale_occupancy",
      linked_task_id: null,
      related_fact_ids: ["fact_hale_lease_rent"],
    },
    {
      id: "cf_hale_lease_expiry",
      organization_id: ORG,
      deal_id: DEAL,
      description: "Lease at 333 W Wacker expires April 2028 — leverage inside a typical hold.",
      source_a_id: "ev_hale_lease",
      source_b_id: "ev_hale_email_lease",
      source_a_label: "Lease.pdf · expires 2028-04-30",
      source_b_label: "Seller email · renewal at then-market, staying in place",
      value_a: null,
      value_b: null,
      difference: null,
      materiality: "material",
      ai_interpretation:
        "Expiry is a negotiation lever, not an automatic occupancy add-back. Renewal is then-market, so rent can step up.",
      recommended_action: "Keep lease treatment unresolved until renewal economics are modeled.",
      owner_user_id: PRIYA,
      status: "investigating",
      resolution_notes: "",
      linked_request_id: "dil_hale_lease",
      linked_adjustment_id: "adj_hale_occupancy",
      linked_task_id: null,
      related_fact_ids: ["fact_hale_lease_expiry"],
    },
    {
      id: "cf_hale_synergy_unsupported",
      organization_id: ORG,
      deal_id: DEAL,
      description: "Identified synergy $90k is possible but unsupported by seller evidence.",
      source_a_id: "ev_hale_loi",
      source_b_id: "ev_hale_ttm_pl",
      source_a_label: "Northline integration model · $90,000",
      source_b_label: "No seller file supports back-office overlap",
      value_a: 90_000,
      value_b: 0,
      difference: 90_000,
      materiality: "notable",
      ai_interpretation:
        "Synergy is a buyer construct. It must stay out of Normalized even if accepted, and should not be paid for in cash at close.",
      recommended_action: "Leave proposed; use contingent consideration if we want to share it.",
      owner_user_id: ELENA,
      status: "unreviewed",
      resolution_notes: "",
      linked_request_id: null,
      linked_adjustment_id: "adj_hale_synergy",
      linked_task_id: null,
      related_fact_ids: [],
    },
  ];
}

function checks(): ReconciliationCheck[] {
  return [
    {
      id: "rc_hale_tax_pl",
      organization_id: ORG,
      deal_id: DEAL,
      name: "FY2024 tax cash vs P&L accrual",
      status: "follow_up_required",
      difference: 240_000,
      notes: "Need book-to-tax bridge",
      conflict_id: "cf_hale_tax_vs_pl",
    },
    {
      id: "rc_hale_payroll",
      organization_id: ORG,
      deal_id: DEAL,
      name: "Payroll vs P&L owner compensation",
      status: "investigating",
      difference: 440_000,
      notes: "Owner line not coded in payroll",
      conflict_id: "cf_hale_payroll_vs_owner",
    },
    {
      id: "rc_hale_qb",
      organization_id: ORG,
      deal_id: DEAL,
      name: "H1 QB vs half TTM",
      status: "unreviewed",
      difference: 150_000,
      notes: "Timing / classification",
      conflict_id: "cf_hale_qb_vs_ttm",
    },
    {
      id: "rc_hale_prod",
      organization_id: ORG,
      deal_id: DEAL,
      name: "Production collections vs recorded revenue",
      status: "unreviewed",
      difference: 250_000,
      notes: "Write-offs / unbilled / origination",
      conflict_id: "cf_hale_prod_vs_rev",
    },
  ];
}

function assumptions(): Assumption[] {
  return [
    {
      id: "asm_hale_owner",
      organization_id: ORG,
      deal_id: DEAL,
      statement: "Replacement-cost partner stack is $1,110,000 vs P&L owner $1,420,000 → $310k add-back.",
      claim_kind: "approved_assumption",
      status: "accepted",
      amount: 310_000,
      linked_adjustment_id: "adj_hale_owner",
      evidence_item_ids: ["ev_hale_ttm_pl", "ev_hale_payroll_v2"],
    },
    {
      id: "asm_hale_legal",
      organization_id: ORG,
      deal_id: DEAL,
      statement: "Schiff Hardin partnership-dispute legal is one-time and will not recur.",
      claim_kind: "approved_assumption",
      status: "accepted",
      amount: 85_000,
      linked_adjustment_id: "adj_hale_legal",
      evidence_item_ids: ["ev_hale_gl"],
    },
    {
      id: "asm_hale_occupancy",
      organization_id: ORG,
      deal_id: DEAL,
      statement: "Market rent is ~$420k vs $540k paid — $120k excess occupancy.",
      claim_kind: "ai_inference",
      status: "pending",
      amount: 120_000,
      linked_adjustment_id: "adj_hale_occupancy",
      evidence_item_ids: ["ev_hale_lease", "ev_hale_note_occupancy"],
    },
    {
      id: "asm_hale_synergy",
      organization_id: ORG,
      deal_id: DEAL,
      statement: "Finance/HR overlap after close is $90k. Unsupported by seller files.",
      claim_kind: "ai_inference",
      status: "pending",
      amount: 90_000,
      linked_adjustment_id: "adj_hale_synergy",
      evidence_item_ids: [],
    },
  ];
}

function risks(): UnderwritingRisk[] {
  return [
    {
      id: "risk_hale_retention",
      organization_id: ORG,
      deal_id: DEAL,
      title: "Attorney retention unsigned",
      detail: "Daniel Mercer is 17% of revenue and has not signed retention terms.",
      severity: "high",
      status: "open",
      evidence_item_ids: ["ev_hale_note_retention", "ev_hale_prod_new"],
    },
    {
      id: "risk_hale_lease",
      organization_id: ORG,
      deal_id: DEAL,
      title: "Lease expiry inside hold",
      detail: "333 W Wacker expires April 2028; renewal is then-market.",
      severity: "high",
      status: "open",
      evidence_item_ids: ["ev_hale_lease", "ev_hale_email_lease"],
    },
    {
      id: "risk_hale_owner_comp",
      organization_id: ORG,
      deal_id: DEAL,
      title: "Owner compensation not payroll-supported",
      detail: "Accepted $310k add-back sits on a P&L line that payroll does not corroborate.",
      severity: "high",
      status: "open",
      evidence_item_ids: ["ev_hale_payroll_v2", "ev_hale_ttm_pl"],
    },
    {
      id: "risk_hale_concentration",
      organization_id: ORG,
      deal_id: DEAL,
      title: "Top-3 concentration 31%",
      detail: "Commercial risk if Mercer or the next two attorneys leave.",
      severity: "medium",
      status: "watching",
      evidence_item_ids: ["ev_hale_prod_new"],
    },
  ];
}

function scenarios(): ValuationScenario[] {
  const seller = 16_800_000;
  const debt = 1_200_000;
  const nwc = 250_000;
  return [
    {
      id: "val_hale_conservative",
      organization_id: ORG,
      deal_id: DEAL,
      key: "conservative",
      name: "Conservative",
      include_owner: true,
      include_legal: true,
      include_occupancy: false,
      include_synergy: false,
      synergy_pct: 0,
      concentration_haircut: 100_000,
      selected_ebitda: 2_395_000,
      ebitda_overridden: false,
      selected_multiple: 5.5,
      multiple_low: 5.0,
      multiple_high: 5.75,
      expected_debt: debt,
      nwc_assumption: nwc,
      other_ppa: 0,
      seller_expectation: seller,
      current_buyer_indication: 13_500_000,
      notes: "Accepted normalized minus a $100k concentration haircut. No occupancy. No synergy.",
    },
    {
      id: "val_hale_base",
      organization_id: ORG,
      deal_id: DEAL,
      key: "base",
      name: "Base",
      include_owner: true,
      include_legal: true,
      include_occupancy: false,
      include_synergy: false,
      synergy_pct: 0,
      concentration_haircut: 0,
      selected_ebitda: 2_495_000,
      ebitda_overridden: false,
      selected_multiple: 6.0,
      multiple_low: 5.75,
      multiple_high: 6.25,
      expected_debt: debt,
      nwc_assumption: nwc,
      other_ppa: 0,
      seller_expectation: seller,
      current_buyer_indication: 14_500_000,
      notes: "Cash at close on accepted normalized $2.495M × 6.0x. Occupancy and synergy stay out.",
    },
    {
      id: "val_hale_upside",
      organization_id: ORG,
      deal_id: DEAL,
      key: "upside",
      name: "Upside",
      include_owner: true,
      include_legal: true,
      include_occupancy: true,
      include_synergy: true,
      synergy_pct: 0.5,
      concentration_haircut: 0,
      selected_ebitda: 2_660_000,
      ebitda_overridden: false,
      selected_multiple: 6.5,
      multiple_low: 6.25,
      multiple_high: 6.75,
      expected_debt: debt,
      nwc_assumption: nwc,
      other_ppa: 0,
      seller_expectation: seller,
      current_buyer_indication: 16_000_000,
      notes: "Adds occupancy $120k and 50% of synergy ($45k). Still a scenario — not accepted financials.",
    },
  ];
}

function factors(): ValuationFactor[] {
  return [
    {
      id: "vf_hale_hist",
      organization_id: ORG,
      deal_id: DEAL,
      scenario_id: "val_hale_base",
      direction: "supporting",
      statement: "Three-year reconstructed revenue is internally consistent once FINAL is superseded (14% growth).",
      evidence_item_ids: ["ev_hale_pl_2023", "ev_hale_pl_2024_updated", "ev_hale_ttm_pl"],
    },
    {
      id: "vf_hale_accepted",
      organization_id: ORG,
      deal_id: DEAL,
      scenario_id: "val_hale_base",
      direction: "supporting",
      statement: "Accepted add-backs ($310k owner + $85k legal) have human approval and source files.",
      evidence_item_ids: ["ev_hale_ttm_pl", "ev_hale_gl"],
    },
    {
      id: "vf_hale_conc",
      organization_id: ORG,
      deal_id: DEAL,
      scenario_id: "val_hale_conservative",
      direction: "pressuring",
      statement: "Top-3 attorney concentration 31%; Mercer 17% without signed retention.",
      evidence_item_ids: ["ev_hale_prod_new", "ev_hale_note_retention"],
    },
    {
      id: "vf_hale_occ",
      organization_id: ORG,
      deal_id: DEAL,
      scenario_id: "val_hale_upside",
      direction: "pressuring",
      statement: "Occupancy add-back is challenged by management — expenses remain after close.",
      evidence_item_ids: ["ev_hale_note_occupancy", "ev_hale_lease"],
    },
    {
      id: "vf_hale_syn",
      organization_id: ORG,
      deal_id: DEAL,
      scenario_id: "val_hale_upside",
      direction: "pressuring",
      statement: "Synergy $90k is a buyer inference with no seller support.",
      evidence_item_ids: [],
    },
    {
      id: "vf_hale_lease",
      organization_id: ORG,
      deal_id: DEAL,
      scenario_id: null,
      direction: "pressuring",
      statement: "Lease expires April 2028; renewal is then-market.",
      evidence_item_ids: ["ev_hale_lease", "ev_hale_email_lease"],
    },
  ];
}

function negotiation(): NegotiationPosition[] {
  return [
    {
      id: "neg_hale_seller_ask",
      organization_id: ORG,
      deal_id: DEAL,
      side: "seller",
      title: "Seller ask $16.8M / 6.2x pro forma",
      body: "Banker indication prices $2.705M pro forma EBITDA, which includes proposed occupancy and unsupported synergy.",
      strength: "counter",
      evidence_item_ids: ["ev_hale_loi"],
      related_issue: "price",
    },
    {
      id: "neg_hale_buyer_base",
      organization_id: ORG,
      deal_id: DEAL,
      side: "buyer",
      title: "Cash at close on accepted normalized",
      body: "Defensible cash is $2.495M × ~6.0x = $14.97M EV before debt/NWC. Do not pay for occupancy or synergy at close.",
      strength: "strong",
      evidence_item_ids: ["ev_hale_ttm_pl"],
      related_issue: "price",
    },
    {
      id: "neg_hale_retention",
      organization_id: ORG,
      deal_id: DEAL,
      side: "buyer",
      title: "Retention holdback / earnout for Mercer book",
      body: "Unsigned retention on 17% of revenue is the strongest factual reason to keep consideration contingent.",
      strength: "strong",
      evidence_item_ids: ["ev_hale_note_retention", "ev_hale_prod_new"],
      related_issue: "retention",
    },
    {
      id: "neg_hale_occ_weak",
      organization_id: ORG,
      deal_id: DEAL,
      side: "buyer",
      title: "Paying for occupancy add-back at close",
      body: "Weak. Management said expenses remain. Using occupancy to justify $16.8M is not fact-supported.",
      strength: "weak",
      evidence_item_ids: ["ev_hale_note_occupancy"],
      related_issue: "occupancy",
    },
    {
      id: "neg_hale_seller_growth",
      organization_id: ORG,
      deal_id: DEAL,
      side: "seller",
      title: "Likely seller counter — growth and TTM run-rate",
      body: "Seller will point to 14% two-year growth and H1 2025 already near a $8.1M run-rate.",
      strength: "counter",
      evidence_item_ids: ["ev_hale_ttm_pl", "ev_hale_qb"],
      related_issue: "price",
    },
  ];
}

function recs(): Recommendation[] {
  return [
    {
      id: "rec_hale_structure",
      organization_id: ORG,
      deal_id: DEAL,
      kind: "structure",
      title: "Cash on accepted normalized; contingent on retention and disputed add-backs",
      body: "Not legal advice. Consider cash at close on accepted normalized EBITDA ($2.495M). Use contingent consideration — seller note, earnout, client-retention holdback, and/or escrow — to bridge attorney retention and the occupancy/synergy items. Do not pay unsupported EBITDA at close.",
      supporting_evidence_ids: [
        "ev_hale_ttm_pl",
        "ev_hale_note_retention",
        "ev_hale_note_occupancy",
        "ev_hale_loi",
      ],
      assumption_ids: ["asm_hale_owner", "asm_hale_legal", "asm_hale_occupancy", "asm_hale_synergy"],
      risk_ids: ["risk_hale_retention", "risk_hale_lease", "risk_hale_owner_comp"],
      alternatives:
        "Lower cash + seller note; earnout on Mercer collections; NWC peg; escrow for book-to-tax and remaining professional services.",
      confidence: 0.78,
      review_status: "pending_review",
    },
  ];
}

function missing(): MissingItem[] {
  return [
    {
      id: "miss_hale_tax_2025",
      organization_id: ORG,
      deal_id: DEAL,
      title: "2025 tax return (or extension + workpapers)",
      why_it_matters: "Without it we cannot confirm TTM tax-basis income or owner personal items.",
      priority: "blocking",
      suggested_seller_request: "Provide the 2025 Form 1065 or the filed extension and year-to-date workpapers.",
      related_line: "Tax / TTM revenue",
      blocking: true,
      linked_request_id: "dil_hale_tax_2025",
      status: "open",
    },
    {
      id: "miss_hale_partner_comp",
      organization_id: ORG,
      deal_id: DEAL,
      title: "Partner compensation detail by partner",
      why_it_matters: "The $310k owner add-back and payroll recon both depend on it. Material to normalized EBITDA.",
      priority: "blocking",
      suggested_seller_request:
        "Provide draws, bonuses, and origination credit by partner for TTM 2025, reconciling to the $1,420,000 P&L line.",
      related_line: "Owner compensation",
      blocking: true,
      linked_request_id: "dil_hale_partner_comp",
      status: "open",
    },
    {
      id: "miss_hale_ps_rest",
      organization_id: ORG,
      deal_id: DEAL,
      title: "Vendor support for remaining $140k professional services",
      why_it_matters: "Email explained $40k of $180k. The rest can still hide owner personal or recurring cost.",
      priority: "blocking",
      suggested_seller_request: "Invoices and a vendor rollforward for professional services after the $85k and $40k items.",
      related_line: "Professional services",
      blocking: true,
      linked_request_id: "dil_hale_ps",
      status: "open",
    },
    {
      id: "miss_hale_retention",
      organization_id: ORG,
      deal_id: DEAL,
      title: "Employment / retention terms for top three attorneys",
      why_it_matters: "31% of revenue. Blocks a final indication.",
      priority: "blocking",
      suggested_seller_request: "Draft retention term sheets for Mercer, Hale, and Cho, including origination treatment.",
      related_line: "Key-person risk",
      blocking: true,
      linked_request_id: "dil_hale_employment",
      status: "open",
    },
    {
      id: "miss_hale_lease_renewal",
      organization_id: ORG,
      deal_id: DEAL,
      title: "Lease renewal economics (not just expiry)",
      why_it_matters: "Occupancy add-back is already challenged; then-market renewal can step rent up.",
      priority: "high",
      suggested_seller_request: "Landlord notice provisions, option language, and any broker opinion of then-market rent.",
      related_line: "Occupancy",
      blocking: true,
      linked_request_id: "dil_hale_lease",
      status: "open",
    },
    {
      id: "miss_hale_synergy",
      organization_id: ORG,
      deal_id: DEAL,
      title: "Support for $90k back-office synergy",
      why_it_matters: "Cannot pay for it at close without a costed integration plan.",
      priority: "medium",
      suggested_seller_request: "Org chart with finance/HR FTEs and current vendor contracts.",
      related_line: "Synergy",
      blocking: false,
      linked_request_id: null,
      status: "open",
    },
    {
      id: "miss_hale_book_tax",
      organization_id: ORG,
      deal_id: DEAL,
      title: "FY2024 book-to-tax bridge",
      why_it_matters: "Explains the $240k cash-vs-accrual gap so we can accept the difference.",
      priority: "high",
      suggested_seller_request: "Schedule M-1 / book-to-tax with owner personal items called out.",
      related_line: "FY2024 revenue",
      blocking: false,
      linked_request_id: "dil_hale_tax_2024",
      status: "open",
    },
  ];
}

function interpretations(): CommunicationInterpretation[] {
  return [
    {
      id: "interp_hale_email_ps",
      organization_id: ORG,
      deal_id: DEAL,
      evidence_item_id: "ev_hale_email_ps",
      kind: "diligence_answer",
      title: "Seller email partially answers professional-services request",
      summary:
        "Claire explains $40k of the $180k as Relativity / e-discovery on Patel (closed June). Remaining ~$140k is coverage counsel + fractional CFO without invoices. Suggest moving dil_hale_ps from follow-up required → received (not complete).",
      suggested_entity_type: "diligence_request",
      suggested_entity_id: "dil_hale_ps",
      suggested_status: "received",
      suggested_notes:
        "Partial seller answer 25 Aug: $40k e-discovery supported; $140k still unexplained. Status should not go to complete.",
      impact_summary:
        "Diligence status only. Accepted financials do not change. The $85k legal add-back stays accepted.",
      review_status: "pending",
      requires_approval: true,
      accepted_financials_would_change: false,
    },
    {
      id: "interp_hale_occ",
      organization_id: ORG,
      deal_id: DEAL,
      evidence_item_id: "ev_hale_note_occupancy",
      kind: "adjustment_challenge",
      title: "Meeting note challenges occupancy add-back",
      summary:
        "Management says they will stay at 333 W Wacker and the occupancy cost does not disappear at close. Approving this interpretation moves adj_hale_occupancy from proposed → needs_review. It does not silently reject the adjustment.",
      suggested_entity_type: "ebitda_adjustment",
      suggested_entity_id: "adj_hale_occupancy",
      suggested_status: "needs_review",
      suggested_notes:
        "Challenged by 26 Aug meeting: expenses remain post-close. Flagged for reconsideration — not rejected.",
      impact_summary:
        "Occupancy leaves the proposed/pro-forma stack and enters needs-review. Normalized is unchanged (occupancy was never accepted).",
      review_status: "pending",
      requires_approval: true,
      accepted_financials_would_change: false,
    },
  ];
}

export function haleEvidenceTables(): EvidenceTables {
  return {
    evidence_items: items(),
    document_versions: versions(),
    extractions: extractions(),
    extracted_facts: facts(),
    conflicts: conflicts(),
    reconciliation_checks: checks(),
    assumptions: assumptions(),
    underwriting_risks: risks(),
    valuation_scenarios: scenarios(),
    valuation_factors: factors(),
    negotiation_positions: negotiation(),
    recommendations: recs(),
    review_decisions: [],
    missing_items: missing(),
    communication_interpretations: interpretations(),
  };
}

function remapId(id: string, dealId: string): string {
  return `${dealId}__${id}`;
}

export function cloneHaleEvidenceOntoDeal(dealId: string, orgId = ORG): EvidenceTables {
  const src = haleEvidenceTables();
  const map = (id: string | null | undefined) => (id ? remapId(id, dealId) : id);
  return {
    evidence_items: src.evidence_items.map((row) => ({
      ...row,
      id: remapId(row.id, dealId),
      organization_id: orgId,
      deal_id: dealId,
      document_id: row.document_id ? remapId(row.document_id, dealId) : null,
      potential_duplicate_of: map(row.potential_duplicate_of) ?? null,
      superseded_by_id: map(row.superseded_by_id) ?? null,
      supersedes_id: map(row.supersedes_id) ?? null,
    })),
    document_versions: src.document_versions.map((row) => ({
      ...row,
      id: remapId(row.id, dealId),
      organization_id: orgId,
      deal_id: dealId,
      evidence_item_id: remapId(row.evidence_item_id, dealId),
      supersedes_id: map(row.supersedes_id) ?? null,
    })),
    extractions: src.extractions.map((row) => ({
      ...row,
      id: remapId(row.id, dealId),
      organization_id: orgId,
      deal_id: dealId,
      evidence_item_id: remapId(row.evidence_item_id, dealId),
    })),
    extracted_facts: src.extracted_facts.map((row) => ({
      ...row,
      id: remapId(row.id, dealId),
      organization_id: orgId,
      deal_id: dealId,
      evidence_item_id: remapId(row.evidence_item_id, dealId),
      extraction_id: row.extraction_id ? remapId(row.extraction_id, dealId) : null,
      conflicting_fact_ids: row.conflicting_fact_ids.map((id) => remapId(id, dealId)),
    })),
    conflicts: src.conflicts.map((row) => ({
      ...row,
      id: remapId(row.id, dealId),
      organization_id: orgId,
      deal_id: dealId,
      source_a_id: remapId(row.source_a_id, dealId),
      source_b_id: remapId(row.source_b_id, dealId),
      related_fact_ids: row.related_fact_ids.map((id) => remapId(id, dealId)),
    })),
    reconciliation_checks: src.reconciliation_checks.map((row) => ({
      ...row,
      id: remapId(row.id, dealId),
      organization_id: orgId,
      deal_id: dealId,
      conflict_id: row.conflict_id ? remapId(row.conflict_id, dealId) : null,
    })),
    assumptions: src.assumptions.map((row) => ({
      ...row,
      id: remapId(row.id, dealId),
      organization_id: orgId,
      deal_id: dealId,
      evidence_item_ids: row.evidence_item_ids.map((id) => remapId(id, dealId)),
    })),
    underwriting_risks: src.underwriting_risks.map((row) => ({
      ...row,
      id: remapId(row.id, dealId),
      organization_id: orgId,
      deal_id: dealId,
      evidence_item_ids: row.evidence_item_ids.map((id) => remapId(id, dealId)),
    })),
    valuation_scenarios: src.valuation_scenarios.map((row) => ({
      ...row,
      id: remapId(row.id, dealId),
      organization_id: orgId,
      deal_id: dealId,
    })),
    valuation_factors: src.valuation_factors.map((row) => ({
      ...row,
      id: remapId(row.id, dealId),
      organization_id: orgId,
      deal_id: dealId,
      scenario_id: row.scenario_id ? remapId(row.scenario_id, dealId) : null,
      evidence_item_ids: row.evidence_item_ids.map((id) => remapId(id, dealId)),
    })),
    negotiation_positions: src.negotiation_positions.map((row) => ({
      ...row,
      id: remapId(row.id, dealId),
      organization_id: orgId,
      deal_id: dealId,
      evidence_item_ids: row.evidence_item_ids.map((id) => remapId(id, dealId)),
    })),
    recommendations: src.recommendations.map((row) => ({
      ...row,
      id: remapId(row.id, dealId),
      organization_id: orgId,
      deal_id: dealId,
      supporting_evidence_ids: row.supporting_evidence_ids.map((id) => remapId(id, dealId)),
      assumption_ids: row.assumption_ids.map((id) => remapId(id, dealId)),
      risk_ids: row.risk_ids.map((id) => remapId(id, dealId)),
    })),
    review_decisions: [],
    missing_items: src.missing_items.map((row) => ({
      ...row,
      id: remapId(row.id, dealId),
      organization_id: orgId,
      deal_id: dealId,
    })),
    communication_interpretations: src.communication_interpretations.map((row) => ({
      ...row,
      id: remapId(row.id, dealId),
      organization_id: orgId,
      deal_id: dealId,
      evidence_item_id: remapId(row.evidence_item_id, dealId),
    })),
  };
}

