import { CURRENT_ORG_ID } from "./constants";
import { haleMessyDocuments } from "./seed-hale-evidence";
import { activity, adj, contact, doc, fact, finding, inference, note, req, task, buildPeriod } from "./seed-helpers";
import type { Database, Deal } from "./types";

const ORG = CURRENT_ORG_ID;
const DEAL = "hale-mercer";
const ELENA = "user_elena";
const MARCUS = "user_marcus";
const PRIYA = "user_priya";
const TOM = "user_tom";

const FY23 = "hale_fy2023";
const FY24 = "hale_fy2024";
const TTM = "hale_ttm2025";

export const haleDeal: Deal = {
  id: DEAL,
  organization_id: ORG,
  name: "Hale & Mercer LLP",
  location_city: "Chicago",
  location_state: "IL",
  owner_user_id: ELENA,
  source: "banker",
  source_detail: "Harris Williams",
  stage: "diligence",
  stage_entered_at: "2026-08-04",
  asking_price: 16_800_000,
  expected_purchase_price: 16_800_000,
  probability: 0.55,
  vertical: "legal",
  vertical_metrics: {
    attorney_count: 18,
    partner_count: 4,
    revenue_per_attorney: 466_667,
    revenue_concentration_top3: 0.31,
    revenue_by_attorney: [
      { name: "Daniel Mercer", revenue: 1_428_000, share: 0.17 },
      { name: "Jonathan Hale", revenue: 672_000, share: 0.08 },
      { name: "Rebecca Cho", revenue: 504_000, share: 0.06 },
    ],
    practice_area_mix: [
      { name: "Litigation", share: 0.42 },
      { name: "Corporate", share: 0.28 },
      { name: "Real Estate", share: 0.18 },
      { name: "Other", share: 0.12 },
    ],
    partner_compensation: 1_420_000,
    attorney_production: [
      { name: "Daniel Mercer", collections: 1_428_000 },
      { name: "Jonathan Hale", collections: 672_000 },
      { name: "Rebecca Cho", collections: 504_000 },
    ],
    matter_concentration: 0.19,
  },
  flags: ["concentration", "lease_expiry", "missing_tax_return", "financial_inconsistency"],
  created_at: "2026-06-12T15:00:00.000Z",
  last_activity_at: "2026-08-26T18:20:00.000Z",
  summary:
    "Northline is in active diligence on Hale & Mercer, an 18-attorney Chicago litigation-and-corporate firm introduced by Harris Williams. Asking price is $16.8M. Accepted add-backs currently lift TTM EBITDA from $2.1M reported to $2.495M normalized; proposed occupancy and synergy items would take pro forma to $2.705M (6.2x). Partner compensation detail and the 2025 tax return remain the gating items.",
  ai_assessment:
    "Revenue has grown 14% over the trailing two years, but approximately 31% of revenue is attributable to the three largest attorneys. Accepted adjustments currently lift EBITDA by $395k (owner compensation and one-time legal). A proposed $120k occupancy add-back and $90k of identified synergies would take pro forma EBITDA to $2.705M.",
  attention_items: [
    "Partner compensation detail hasn't been received",
    "$180k professional-services expense requires explanation",
    "Largest attorney represents 17% of revenue",
    "Lease expires within 18 months",
    "Seller has not provided 2025 tax return",
  ],
  last_reviewed_at: "2026-08-24T12:00:00.000Z",
  template_id: "tpl_law_firm",
  external_system: "mymavacy",
  external_deal_id: "mm_hale_mercer",
  external_deal_url: "https://app.mymavacy.example/deals/hale-mercer",
  external_imported_at: "2026-07-18T10:00:00.000Z",
  external_updated_at: "2026-08-26T12:00:00.000Z",
};

const fy23 = buildPeriod({
  id: FY23,
  dealId: DEAL,
  label: "FY2023",
  type: "fiscal_year",
  start: "2023-01-01",
  end: "2023-12-31",
  latest: false,
  order: 1,
  revenue: 7_370_000,
  direct: 2_063_600,
  opex: 3_606_400,
  ebitda: 1_700_000,
  opexDetail: {
    opex_owner: 1_180_000,
    opex_staff: 760_000,
    opex_occupancy: 500_000,
    opex_marketing: 740_000,
    opex_professional_services: 168_000,
    opex_insurance: 140_000,
    opex_technology: 118_000,
    opex_other: 400,
  },
  documentId: "doc_hale_fy23_pl",
  documentName: "Hale_Mercer_FY2023_PL.pdf",
});

const fy24 = buildPeriod({
  id: FY24,
  dealId: DEAL,
  label: "FY2024",
  type: "fiscal_year",
  start: "2024-01-01",
  end: "2024-12-31",
  latest: false,
  order: 2,
  revenue: 7_720_000,
  direct: 2_161_600,
  opex: 3_658_400,
  ebitda: 1_900_000,
  opexDetail: {
    opex_owner: 1_220_000,
    opex_staff: 820_000,
    opex_occupancy: 520_000,
    opex_marketing: 520_000,
    opex_professional_services: 280_000,
    opex_insurance: 152_000,
    opex_technology: 146_000,
    opex_other: 400,
  },
  documentId: "doc_hale_fy24_pl",
  documentName: "Hale_Mercer_FY2024_PL.pdf",
});

const ttm = buildPeriod({
  id: TTM,
  dealId: DEAL,
  label: "TTM 2025",
  type: "ttm",
  start: "2024-07-01",
  end: "2025-06-30",
  latest: true,
  order: 3,
  revenue: 8_400_000,
  direct: 2_352_000,
  opex: 3_948_000,
  ebitda: 2_100_000,
  opexDetail: {
    opex_owner: 1_420_000,
    opex_staff: 955_000,
    opex_occupancy: 540_000,
    opex_marketing: 410_000,
    opex_professional_services: 248_000,
    opex_insurance: 165_000,
    opex_technology: 190_000,
    opex_other: 20_000,
  },
  documentId: "doc_hale_ttm_pl",
  documentName: "Hale_Mercer_TTM_2025_PL.pdf",
});

export function haleSlice(): Pick<
  Database,
  | "contacts"
  | "financial_periods"
  | "financial_metrics"
  | "ebitda_adjustments"
  | "documents"
  | "diligence_requests"
  | "ai_findings"
  | "tasks"
  | "notes"
  | "activities"
  | "audit_events"
> {
  return {
    contacts: [
      contact({
        id: "con_hale_jonathan",
        deal_id: DEAL,
        name: "Jonathan Hale",
        title: "Managing Partner",
        email: "jhale@halemercer.com",
        phone: "+1 312 555 0144",
        is_primary: true,
      }),
      contact({
        id: "con_hale_daniel",
        deal_id: DEAL,
        name: "Daniel Mercer",
        title: "Partner, Litigation",
        email: "dmercer@halemercer.com",
        phone: "+1 312 555 0188",
        is_primary: false,
      }),
      contact({
        id: "con_hale_claire",
        deal_id: DEAL,
        name: "Claire Hoffman",
        title: "Firm Administrator",
        email: "choffman@halemercer.com",
        phone: "+1 312 555 0110",
        is_primary: false,
      }),
    ],
    financial_periods: [fy23.period, fy24.period, ttm.period],
    financial_metrics: [...fy23.metrics, ...fy24.metrics, ...ttm.metrics],
    ebitda_adjustments: [
      adj({
        id: "adj_hale_owner",
        dealId: DEAL,
        periodId: TTM,
        category: "compensation",
        description: "Owner compensation normalization",
        amount: 310_000,
        source: "P&L owner comp vs replacement-cost study",
        origin: "ai",
        status: "accepted",
        confidence: 0.91,
        notes: "Accepted after Marcus compared TTM owner draw to a three-partner replacement stack.",
        provenance: {
          ...inference(
            "doc_hale_ttm_pl",
            "Hale_Mercer_TTM_2025_PL.pdf",
            "Owner compensation",
            "1420000",
            0.91
          ),
          approval_status: "approved_assumption",
        },
      }),
      adj({
        id: "adj_hale_legal",
        dealId: DEAL,
        periodId: TTM,
        category: "one_time",
        description: "One-time legal expense",
        amount: 85_000,
        source: "Professional-services detail, partnership dispute",
        origin: "manual",
        status: "accepted",
        confidence: 0.94,
        notes: "Confirmed as a concluded partnership dispute; not expected to recur.",
        provenance: fact(
          "doc_hale_gl_ps",
          "Hale_Mercer_GL_Professional_Services.xlsx",
          "Vendor: Schiff Hardin matter",
          "85000",
          0.94,
          "approved_assumption"
        ),
      }),
      adj({
        id: "adj_hale_occupancy",
        dealId: DEAL,
        periodId: TTM,
        category: "occupancy",
        description: "Excess occupancy expense",
        amount: 120_000,
        source: "Lease vs market rent",
        origin: "ai",
        status: "proposed",
        confidence: 0.72,
        notes: "",
        provenance: inference(
          "doc_hale_lease",
          "333_W_Wacker_Office_Lease.pdf",
          "Article 3 — Rent",
          "540000 occupancy vs estimated $420k market",
          0.72
        ),
      }),
      adj({
        id: "adj_hale_synergy",
        dealId: DEAL,
        periodId: TTM,
        category: "synergy",
        description: "Identified synergies",
        amount: 90_000,
        source: "Back-office consolidation (not a quality-of-earnings add-back)",
        origin: "ai",
        status: "proposed",
        confidence: 0.64,
        notes: "",
        provenance: inference(
          null,
          null,
          "Northline integration model",
          "90000 finance/HR overlap",
          0.64
        ),
      }),
    ],
    documents: [
      doc({
        id: "doc_hale_fy23_pl",
        dealId: DEAL,
        filename: "Hale_Mercer_FY2023_PL.pdf",
        folder: "financials",
        uploadedAt: "2026-07-18T14:10:00.000Z",
        uploadedBy: TOM,
        classification: "income_statement",
        pages: 8,
        payload: { period: "FY2023", revenue: 7370000, ebitda: 1700000 },
        linked: ["dil_hale_pls"],
      }),
      doc({
        id: "doc_hale_fy24_pl",
        dealId: DEAL,
        filename: "Hale_Mercer_FY2024_PL.pdf",
        folder: "financials",
        uploadedAt: "2026-07-18T14:12:00.000Z",
        uploadedBy: TOM,
        classification: "income_statement",
        pages: 9,
        payload: { period: "FY2024", revenue: 7720000, ebitda: 1900000 },
        linked: ["dil_hale_pls"],
      }),
      doc({
        id: "doc_hale_ttm_pl",
        dealId: DEAL,
        filename: "Hale_Mercer_TTM_2025_PL.pdf",
        folder: "financials",
        uploadedAt: "2026-08-05T16:40:00.000Z",
        uploadedBy: MARCUS,
        classification: "income_statement",
        pages: 11,
        payload: { period: "TTM 2025", revenue: 8400000, ebitda: 2100000 },
        linked: ["dil_hale_pls", "dil_hale_ps"],
      }),
      doc({
        id: "doc_hale_tax_2024",
        dealId: DEAL,
        filename: "Hale_Mercer_2024_Form_1065.pdf",
        folder: "tax",
        uploadedAt: "2026-07-22T11:05:00.000Z",
        uploadedBy: TOM,
        classification: "tax_return",
        pages: 46,
        payload: { year: 2024, form: "1065" },
        linked: ["dil_hale_tax_2024"],
      }),
      doc({
        id: "doc_hale_payroll",
        dealId: DEAL,
        filename: "Hale_Mercer_Payroll_Register_TTM.xlsx",
        folder: "payroll",
        uploadedAt: "2026-08-08T13:22:00.000Z",
        uploadedBy: MARCUS,
        classification: "payroll_register",
        pages: 1,
        payload: { partner_comp_shown: 980000 },
        linked: ["dil_hale_payroll"],
        status: "needs_review",
        confidence: 0.78,
      }),
      doc({
        id: "doc_hale_production",
        dealId: DEAL,
        filename: "Hale_Mercer_Attorney_Production_2025.xlsx",
        folder: "attorney_production",
        uploadedAt: "2026-08-22T15:18:00.000Z",
        uploadedBy: TOM,
        classification: "attorney_production",
        pages: 4,
        payload: { top_attorney: "Daniel Mercer", share: 0.17, top3: 0.31 },
        linked: ["dil_hale_production"],
      }),
      doc({
        id: "doc_hale_lease",
        dealId: DEAL,
        filename: "333_W_Wacker_Office_Lease.pdf",
        folder: "real_estate",
        uploadedAt: "2026-07-29T10:00:00.000Z",
        uploadedBy: TOM,
        classification: "office_lease",
        pages: 42,
        payload: { address: "333 W Wacker, Chicago", expiry: "2028-04-30", rent: 540000 },
        linked: ["dil_hale_lease"],
      }),
      doc({
        id: "doc_hale_nda",
        dealId: DEAL,
        filename: "Hale_Mercer_NDA_Executed.pdf",
        folder: "legal",
        uploadedAt: "2026-06-20T09:30:00.000Z",
        uploadedBy: ELENA,
        classification: "nda",
        pages: 7,
        linked: ["dil_hale_nda"],
      }),
      doc({
        id: "doc_hale_cim",
        dealId: DEAL,
        filename: "Hale_Mercer_CIM.pdf",
        folder: "corporate",
        uploadedAt: "2026-06-14T17:00:00.000Z",
        uploadedBy: ELENA,
        classification: "cim",
        pages: 38,
        payload: { asking_price: 16800000 },
      }),
      doc({
        id: "doc_hale_org",
        dealId: DEAL,
        filename: "Hale_Mercer_Org_Chart.pdf",
        folder: "corporate",
        uploadedAt: "2026-07-21T12:44:00.000Z",
        uploadedBy: TOM,
        classification: "org_chart",
        pages: 2,
        linked: ["dil_hale_org"],
      }),
      doc({
        id: "doc_hale_engagement",
        dealId: DEAL,
        filename: "Northline_Hale_Mercer_Engagement_Letter.pdf",
        folder: "legal",
        uploadedAt: "2026-06-18T15:12:00.000Z",
        uploadedBy: ELENA,
        classification: "engagement_letter",
        pages: 9,
        linked: ["dil_hale_engagement"],
      }),
      doc({
        id: "doc_hale_gl_ps",
        dealId: DEAL,
        filename: "Hale_Mercer_GL_Professional_Services.xlsx",
        folder: "financials",
        uploadedAt: "2026-08-11T19:05:00.000Z",
        uploadedBy: MARCUS,
        classification: "general_ledger_excerpt",
        status: "needs_review",
        pages: 1,
        payload: { professional_services_ttm: 248000, one_time_legal: 85000 },
        linked: ["dil_hale_ps"],
        confidence: 0.81,
      }),
      doc({
        id: "doc_hale_partnership",
        dealId: DEAL,
        filename: "Hale_Mercer_Partnership_Agreement.pdf",
        folder: "corporate",
        uploadedAt: "2026-07-24T08:50:00.000Z",
        uploadedBy: PRIYA,
        classification: "partnership_agreement",
        pages: 31,
      }),
      ...haleMessyDocuments(),
    ],
    diligence_requests: [
      req({
        id: "dil_hale_pls",
        dealId: DEAL,
        category: "financial",
        question: "Provide FY2023, FY2024, and TTM 2025 P&Ls with OpEx detail.",
        status: "complete",
        owner: MARCUS,
        counterparty: "Claire Hoffman",
        due: "2026-08-01",
        docs: ["doc_hale_fy23_pl", "doc_hale_fy24_pl", "doc_hale_ttm_pl"],
        priority: "critical",
      }),
      req({
        id: "dil_hale_monthly",
        dealId: DEAL,
        category: "financial",
        question: "Monthly financials for the TTM 2025 period.",
        status: "complete",
        owner: MARCUS,
        counterparty: "Claire Hoffman",
        due: "2026-08-08",
        priority: "high",
      }),
      req({
        id: "dil_hale_ar",
        dealId: DEAL,
        category: "financial",
        question: "AR aging with WIP and realization by partner.",
        status: "requested",
        owner: MARCUS,
        counterparty: "Claire Hoffman",
        due: "2026-08-20",
        priority: "high",
      }),
      req({
        id: "dil_hale_ps",
        dealId: DEAL,
        category: "financial",
        question: "Vendor-level support for TTM professional-services expense after removing the $85k one-time legal item.",
        status: "follow_up_required",
        owner: MARCUS,
        counterparty: "Claire Hoffman",
        due: "2026-08-18",
        docs: ["doc_hale_gl_ps"],
        notes: "$180k remains unexplained.",
        ai: true,
        priority: "critical",
      }),
      req({
        id: "dil_hale_wc",
        dealId: DEAL,
        category: "financial",
        question: "Working-capital bridge and target net working capital proposal.",
        status: "complete",
        owner: MARCUS,
        due: "2026-08-12",
      }),
      req({
        id: "dil_hale_clients",
        dealId: DEAL,
        category: "revenue_clients",
        question: "Client list with trailing-twelve-month collections and concentration.",
        status: "requested",
        owner: ELENA,
        counterparty: "Jonathan Hale",
        due: "2026-08-29",
        priority: "high",
      }),
      req({
        id: "dil_hale_top20",
        dealId: DEAL,
        category: "revenue_clients",
        question: "Top 20 clients / matters by collections, with tenure.",
        status: "complete",
        owner: ELENA,
        due: "2026-08-10",
      }),
      req({
        id: "dil_hale_production",
        dealId: DEAL,
        category: "revenue_clients",
        question: "Attorney production report for TTM 2025.",
        status: "complete",
        owner: MARCUS,
        docs: ["doc_hale_production"],
        due: "2026-08-15",
        priority: "high",
      }),
      req({
        id: "dil_hale_mix",
        dealId: DEAL,
        category: "revenue_clients",
        question: "Contingency vs hourly mix and realization rates.",
        status: "complete",
        owner: MARCUS,
        due: "2026-08-16",
      }),
      req({
        id: "dil_hale_employment",
        dealId: DEAL,
        category: "employees_attorneys",
        question: "Employment terms and historical retention for the top three attorneys (31% of revenue).",
        status: "requested",
        owner: PRIYA,
        counterparty: "Jonathan Hale",
        due: "2026-08-21",
        ai: true,
        priority: "critical",
      }),
      req({
        id: "dil_hale_org",
        dealId: DEAL,
        category: "employees_attorneys",
        question: "Current organizational chart with partner vs associate headcount.",
        status: "complete",
        owner: TOM,
        docs: ["doc_hale_org"],
        due: "2026-07-25",
      }),
      req({
        id: "dil_hale_attrition",
        dealId: DEAL,
        category: "employees_attorneys",
        question: "Associate attrition for the past three years.",
        status: "complete",
        owner: TOM,
        due: "2026-08-14",
      }),
      req({
        id: "dil_hale_partner_comp",
        dealId: DEAL,
        category: "compensation",
        question: "Partner compensation detail by partner, including draws, bonuses, and origination credit.",
        status: "requested",
        owner: MARCUS,
        counterparty: "Jonathan Hale",
        due: "2026-08-15",
        notes: "Gating item. File promised 8/15 and not received.",
        priority: "critical",
      }),
      req({
        id: "dil_hale_payroll",
        dealId: DEAL,
        category: "compensation",
        question: "Reconcile partner compensation in the payroll register to compensation expense on the P&L.",
        status: "follow_up_required",
        owner: MARCUS,
        docs: ["doc_hale_payroll", "doc_hale_ttm_pl"],
        due: "2026-08-22",
        ai: true,
        priority: "critical",
      }),
      req({
        id: "dil_hale_bonus",
        dealId: DEAL,
        category: "compensation",
        question: "Bonus and origination plan documentation.",
        status: "complete",
        owner: MARCUS,
        due: "2026-08-09",
      }),
      req({
        id: "dil_hale_nda",
        dealId: DEAL,
        category: "legal",
        question: "Executed NDA.",
        status: "complete",
        owner: ELENA,
        docs: ["doc_hale_nda"],
        due: "2026-06-21",
      }),
      req({
        id: "dil_hale_litigation",
        dealId: DEAL,
        category: "legal",
        question: "Schedule of pending litigation and material claims against the firm.",
        status: "complete",
        owner: PRIYA,
        due: "2026-08-11",
      }),
      req({
        id: "dil_hale_malpractice",
        dealId: DEAL,
        category: "legal",
        question: "Malpractice claims history and carrier loss runs (five years).",
        status: "requested",
        owner: PRIYA,
        counterparty: "Claire Hoffman",
        due: "2026-08-30",
        priority: "high",
      }),
      req({
        id: "dil_hale_tax_2024",
        dealId: DEAL,
        category: "tax",
        question: "2024 Form 1065 and K-1s.",
        status: "complete",
        owner: MARCUS,
        docs: ["doc_hale_tax_2024"],
        due: "2026-07-25",
      }),
      req({
        id: "dil_hale_tax_2025",
        dealId: DEAL,
        category: "tax",
        question: "2025 tax return (or filed extension and workpapers).",
        status: "requested",
        owner: TOM,
        counterparty: "Claire Hoffman",
        due: "2026-08-12",
        notes: "Seller has not provided. Extension status unconfirmed.",
        priority: "critical",
      }),
      req({
        id: "dil_hale_nexus",
        dealId: DEAL,
        category: "tax",
        question: "Sales-tax / nexus analysis for out-of-state matters.",
        status: "na",
        owner: MARCUS,
        notes: "Illinois partnership; no sales-tax exposure on legal services.",
      }),
      req({
        id: "dil_hale_lease",
        dealId: DEAL,
        category: "real_estate",
        question: "Office lease at 333 W Wacker — confirm expiry, renewal options, and market rent.",
        status: "follow_up_required",
        owner: PRIYA,
        docs: ["doc_hale_lease"],
        due: "2026-08-19",
        ai: true,
        priority: "high",
      }),
      req({
        id: "dil_hale_ffe",
        dealId: DEAL,
        category: "real_estate",
        question: "Personal property / FF&E schedule.",
        status: "na",
        owner: TOM,
        notes: "Immaterial relative to purchase price.",
      }),
      req({
        id: "dil_hale_tech",
        dealId: DEAL,
        category: "technology",
        question: "Practice-management system export and data-room inventory.",
        status: "complete",
        owner: TOM,
        due: "2026-08-07",
      }),
      req({
        id: "dil_hale_engagement",
        dealId: DEAL,
        category: "operations",
        question: "Standard engagement letter and billing policies.",
        status: "complete",
        owner: ELENA,
        docs: ["doc_hale_engagement"],
        due: "2026-07-20",
      }),
    ],
    ai_findings: [
      finding({
        id: "find_hale_marketing",
        dealId: DEAL,
        title: "Marketing spend vs revenue growth",
        question:
          "Marketing expense declined from $740k to $410k while revenue increased 14%. Was there a change in classification, channel strategy, or owner-paid marketing?",
        docs: ["doc_hale_fy23_pl", "doc_hale_ttm_pl"],
        assignee: MARCUS,
        provenance: inference(
          "doc_hale_ttm_pl",
          "FY2023 P&L, TTM 2025 P&L",
          "Marketing",
          "740000 → 410000",
          0.88
        ),
      }),
      finding({
        id: "find_hale_payroll",
        dealId: DEAL,
        title: "Payroll vs P&L compensation",
        question:
          "Partner compensation shown in the payroll file does not reconcile with compensation expense in the P&L. Please provide a reconciliation.",
        docs: ["doc_hale_payroll", "doc_hale_ttm_pl"],
        linked: "dil_hale_payroll",
        assignee: MARCUS,
        provenance: inference(
          "doc_hale_payroll",
          "Payroll register vs P&L",
          "Partner compensation",
          "payroll 980000 vs P&L owner 1420000",
          0.9
        ),
      }),
      finding({
        id: "find_hale_mercer",
        dealId: DEAL,
        title: "Daniel Mercer concentration",
        question:
          "Daniel Mercer represents approximately 17% of firm revenue. Please provide employment terms and historical retention information for the top three attorneys (31% of revenue).",
        docs: ["doc_hale_production"],
        linked: "dil_hale_employment",
        assignee: PRIYA,
        provenance: inference(
          "doc_hale_production",
          "Attorney production report",
          "Collections by attorney",
          "Daniel Mercer 17%; top 3 31%",
          0.95
        ),
      }),
      finding({
        id: "find_hale_ps",
        dealId: DEAL,
        title: "Unexplained professional services",
        question:
          "$180k of professional-services expense in TTM 2025 is unexplained after removing the $85k one-time legal item. Please provide vendor detail.",
        docs: ["doc_hale_ttm_pl", "doc_hale_gl_ps"],
        linked: "dil_hale_ps",
        assignee: MARCUS,
        provenance: inference(
          "doc_hale_gl_ps",
          "P&L / GL",
          "Professional services",
          "248000 − 85000 = 180000 unexplained",
          0.86
        ),
      }),
      finding({
        id: "find_hale_lease",
        dealId: DEAL,
        title: "Lease expiry vs hold period",
        question:
          "Office lease at 333 W Wacker expires April 2028 (within 18 months of a typical hold). Confirm renewal options and market rent.",
        docs: ["doc_hale_lease"],
        linked: "dil_hale_lease",
        assignee: PRIYA,
        provenance: inference(
          "doc_hale_lease",
          "Office lease",
          "Term / expiration",
          "Expires April 2028",
          0.97
        ),
      }),
    ],
    tasks: [
      task({
        id: "task_hale_comp",
        dealId: DEAL,
        title: "Review partner compensation file",
        owner: MARCUS,
        due: "2026-08-27",
        created: "2026-08-18T13:00:00.000Z",
      }),
      task({
        id: "task_hale_tax",
        dealId: DEAL,
        title: "Chase 2025 tax return",
        owner: TOM,
        due: "2026-08-29",
        created: "2026-08-12T10:00:00.000Z",
      }),
      task({
        id: "task_hale_ps",
        dealId: DEAL,
        title: "Draft follow-up on professional services",
        owner: ELENA,
        due: "2026-09-02",
        created: "2026-08-20T09:00:00.000Z",
      }),
    ],
    notes: [
      note({
        id: "note_hale_elena",
        dealId: DEAL,
        author: ELENA,
        body: "Partner economics are the gating item. Jonathan agreed to send compensation detail last week; still missing as of this morning. I do not want LOI language drafted until Marcus has seen the file.",
        at: "2026-08-26T18:20:00.000Z",
      }),
      note({
        id: "note_hale_marcus",
        dealId: DEAL,
        author: MARCUS,
        body: "Marketing declined $330k while revenue rose 14%. Either classification moved into owner-paid channels or the firm pulled spend. Need Claire to walk the GL before I treat 25% margin as durable.",
        at: "2026-08-21T15:10:00.000Z",
      }),
      note({
        id: "note_hale_priya",
        dealId: DEAL,
        author: PRIYA,
        body: "333 W Wacker expires April 2028. On a typical five-year hold that is inside the window. Renewal option language is thin — confirm with landlord counsel before we underwrite occupancy add-backs.",
        at: "2026-08-15T11:42:00.000Z",
      }),
    ],
    activities: [
      activity({
        id: "act_hale_note_26",
        dealId: DEAL,
        actor: ELENA,
        kind: "note",
        title: "Elena Vargas added a note",
        body: "Partner economics are the gating item. Compensation file still outstanding.",
        at: "2026-08-26T18:20:00.000Z",
      }),
      activity({
        id: "act_hale_adj_owner",
        dealId: DEAL,
        actor: MARCUS,
        kind: "adjustment_status",
        title: "Accepted owner compensation normalization",
        body: "Moved +$310,000 owner compensation add-back to Accepted. Normalized EBITDA is now $2,495,000.",
        at: "2026-08-25T16:05:00.000Z",
        meta: { adjustment_id: "adj_hale_owner", status: "accepted" },
      }),
      activity({
        id: "act_hale_req_comp",
        dealId: DEAL,
        actor: MARCUS,
        kind: "diligence_status",
        title: "Requested partner compensation detail",
        body: "Sent follow-up to Jonathan Hale. Due 15 Aug; still open.",
        at: "2026-08-24T14:30:00.000Z",
        meta: { request_id: "dil_hale_partner_comp" },
      }),
      activity({
        id: "act_hale_prod",
        dealId: DEAL,
        actor: TOM,
        kind: "document_upload",
        title: "Uploaded attorney production report",
        body: "Hale_Mercer_Attorney_Production_2025.xlsx classified as attorney production.",
        at: "2026-08-22T15:18:00.000Z",
      }),
      activity({
        id: "act_hale_note_marcus",
        dealId: DEAL,
        actor: MARCUS,
        kind: "note",
        title: "Marcus Webb added a note",
        body: "Marketing decline needs a classification check before margin is treated as durable.",
        at: "2026-08-21T15:10:00.000Z",
      }),
      activity({
        id: "act_hale_finding",
        dealId: DEAL,
        actor: null,
        kind: "finding_action",
        title: "AI findings generated from TTM P&L and production file",
        body: "Five follow-up questions posted, including marketing classification, payroll recon, and Mercer concentration.",
        at: "2026-08-18T20:00:00.000Z",
      }),
      activity({
        id: "act_hale_note_priya",
        dealId: DEAL,
        actor: PRIYA,
        kind: "note",
        title: "Priya Shah added a note",
        body: "Lease expiry sits inside a typical hold. Confirm renewal options before underwriting occupancy.",
        at: "2026-08-15T11:42:00.000Z",
      }),
      activity({
        id: "act_hale_adj_legal",
        dealId: DEAL,
        actor: MARCUS,
        kind: "adjustment_status",
        title: "Accepted one-time legal expense",
        body: "Partnership-dispute legal fees of $85,000 marked Accepted.",
        at: "2026-08-12T17:25:00.000Z",
      }),
      activity({
        id: "act_hale_gl",
        dealId: DEAL,
        actor: MARCUS,
        kind: "document_upload",
        title: "Uploaded professional-services GL excerpt",
        body: "Hale_Mercer_GL_Professional_Services.xlsx marked Needs Review.",
        at: "2026-08-11T19:05:00.000Z",
      }),
      activity({
        id: "act_hale_stage",
        dealId: DEAL,
        actor: ELENA,
        kind: "stage_change",
        title: "Stage moved to Diligence",
        body: "Advanced from Financial Review to Diligence after TTM P&L landed.",
        at: "2026-08-04T13:00:00.000Z",
        meta: { from: "financial_review", to: "diligence" },
      }),
      activity({
        id: "act_hale_ttm",
        dealId: DEAL,
        actor: MARCUS,
        kind: "document_upload",
        title: "Uploaded TTM 2025 P&L",
        body: "Hale_Mercer_TTM_2025_PL.pdf analyzed. Reported EBITDA $2,100,000.",
        at: "2026-08-05T16:40:00.000Z",
      }),
      activity({
        id: "act_hale_cim",
        dealId: DEAL,
        actor: ELENA,
        kind: "document_upload",
        title: "Uploaded CIM",
        body: "Hale_Mercer_CIM.pdf from Harris Williams. Asking price $16.8M.",
        at: "2026-06-14T17:00:00.000Z",
      }),
    ],
    audit_events: [
      {
        id: "aud_hale_stage",
        organization_id: ORG,
        deal_id: DEAL,
        actor_user_id: ELENA,
        entity_type: "deal",
        entity_id: DEAL,
        action: "stage_change",
        before: { stage: "financial_review" },
        after: { stage: "diligence", stage_entered_at: "2026-08-04" },
        occurred_at: "2026-08-04T13:00:00.000Z",
      },
      {
        id: "aud_hale_owner",
        organization_id: ORG,
        deal_id: DEAL,
        actor_user_id: MARCUS,
        entity_type: "ebitda_adjustment",
        entity_id: "adj_hale_owner",
        action: "status_change",
        before: { status: "proposed" },
        after: { status: "accepted" },
        occurred_at: "2026-08-25T16:05:00.000Z",
      },
    ],
  };
}
